//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by F:\Tmaxnet\Presentation\Tmxml\Tm_xml6.rc
//
#define IDS_TMXML                       1
#define IDD_ABOUTBOX_TMXML              1
#define IDB_TMXML                       1
#define IDI_ABOUTDLL                    1
#define IDS_TMXML_PPG                   2
#define IDC_ADD                         3
#define IDC_REMOVE                      4
#define IDS_TMXML_PPG_CAPTION           200
#define IDD_PROPPAGE_TMXML              200
#define IDD_FRAME                       201
#define IDS_TMXML_CREATEFRAMEFAILED     201
#define IDC_TMTOOL                      202
#define IDS_TMXML_LOADFILEFAILED        202
#define IDD_SESSION                     202
#define IDD_SESSION_PAGE                202
#define IDD_VIEWER_PAGE                 202
#define IDC_TMVIEW                      203
#define IDS_TMXML_FILENOTFOUND          203
#define IDD_IMAGE_PAGE                  203
#define IDB_MEDIA_CTRL                  203
#define IDC_COPIES                      203
#define IDS_TMXML_NOTINITIALIZED        204
#define IDC_TMPRINT                     204
#define IDD_TMX_PAGE                    204
#define IDC_DRAG                        204
#define IDC_TMX_SOURCE                  205
#define IDD_ABOUT_PAGE                  205
#define IDC_WAIT_ARROW                  205
#define IDC_TMX_FILENAME                206
#define IDD_MEDIA_PAGE                  206
#define IDC_NODROP                      206
#define IDC_TREE                        207
#define IDD_DOWNLOAD_PROGRESS           207
#define IDC_TMX_XML                     207
#define IDC_PROGRESS                    208
#define IDD_TOOLBAR_PAGE                208
#define IDC_QUEUE                       208
#define IDC_PROGCTRL1                   209
#define ID_ABORT                        210
#define IDC_STATUS                      211
#define IDC_NAME                        212
#define IDC_PROGRESS_BAR                212
#define IDC_COPYRIGHT                   213
#define IDC_PPTOOL_FLAT                 213
#define IDC_PHONE                       214
#define IDC_PPTOOL_ROWS                 214
#define IDC_EMAIL                       215
#define IDC_PROGRESS_DELAY              215
#define IDC_TMPOWER                     216
#define IDC_EDIT                        220
#define IDC_MESSAGE                     220
#define IDC_DOWNLOAD_BYTES              221
#define IDC_DOWNLOAD_STATUS             224
#define IDC_DOWNLOAD_JOB                225
#define IDC_PRINTERS                    225
#define IDC_TEMPLATES                   226
#define IDC_CURRENT_SESSION             227
#define IDC_LIST                        228
#define IDC_MINIMIZE_COLOR_DEPTH        228
#define IDC_COMBINE_PRINT_PAGES         229
#define IDC_SAVE_AS                     230
#define IDC_TARGET_URL                  231
#define IDC_REQUEST                     232
#define IDC_HEADERS                     233
#define IDC_HEADERS_LABEL               234
#define IDC_RESPONSE_CODE               234
#define IDC_REQUEST_LABEL               235
#define IDC_TARGET_LABEL                236
#define IDC_SAVE_REQUEST                237
#define IDC_SAVE_RESPONSE               238
#define IDC_FILENAME                    239
#define IDC_RESPONSE                    239
#define IDC_TREES                       239
#define IDC_RESPONSE_LABEL              240
#define IDC_QUEUE_TREATMENTS            240
#define IDC_DIM_PIXELS                  241
#define IDC_POST                        241
#define IDC_QUEUE_PAGES                 241
#define IDC_DIM_INCHES                  242
#define IDC_PAGE_FROM                   242
#define IDC_BITSPERPIXEL                243
#define IDC_PAGE_TO                     243
#define IDC_SIZEDISK                    244
#define IDC_FROM_LABEL                  244
#define IDC_SIZERAM                     245
#define IDC_TO_LABEL                    245
#define IDC_PAGE                        246
#define IDC_COMPRESSION                 247
#define IDC_INTERNET_PORT               247
#define IDC_IMAGE_TYPE                  248
#define IDC_PROXY_ADDRESS               249
#define IDC_PROXY_ADDRESS_LABEL         251
#define IDC_PROXY_PORT_LABEL            252
#define IDC_PROXY_PORT                  253
#define IDC_DEFAULT_PORT                254
#define IDC_ASSIGN_PORT                 255
#define IDC_TMBROWSE                    255
#define IDC_PROXY_SERVER                256
#define IDC_CHECK1                      257
#define IDC_RESIZABLECALLOUTS           257
#define IDC_TOOLBAR                     258
#define IDC_TEXT                        259
#define IDC_PAGES                       260
#define IDC_CACHED                      261
#define IDC_SOURCE                      262
#define IDC_ERROR_MESSAGE               263
#define IDC_COMPLETE                    264
#define IDC_ABORTED                     265
#define IDC_LPARAM                      266
#define IDC_REMOTE                      267
#define IDC_ERROR                       268
#define IDC_MAX_PROGRESS                270
#define IDD_TOOLS_PAGE                  301
#define IDB_TBBITMAPS                   337
#define IDD_DIAGNOSTIC_PAGE             515
#define IDD_REVISIONS_PAGE              515
#define IDD_PRINT_PROGRESS              516
#define IDD_PRINT_PAGE                  517
#define IDD_TREATMENT_PAGE              518
#define IDD_SELECT_PRINT                519
#define IDD_NAVIGATE                    520
#define IDD_PB_TOOLBAR                  521
#define IDD_PB_LIST                     522
#define IDD_PB_TEXT                     523
#define IDD_PB_BAND                     524
#define IDD_DOWNLOAD_PAGE               525
#define IDC_COLLATE                     744
#define IDC_RED                         1005
#define IDC_GREEN                       1006
#define IDC_BLUE                        1007
#define IDC_MAGENTA                     1008
#define IDC_YELLOW                      1009
#define IDC_CYAN                        1010
#define IDC_BLACK                       1011
#define IDC_GREY                        1012
#define IDC_ENABLEERRORS                1013
#define IDC_WHITE                       1013
#define IDC_FLOAT_PROGRESS              1014
#define IDC_DRAWTOOL                    1014
#define IDC_CONFIRM_BATCH               1015
#define IDC_HIGHLIGHT                   1015
#define IDC_REDACT                      1016
#define IDC_SHOW_PAGE_NAVIGATION        1016
#define IDC_DARKRED                     1017
#define IDC_DARKBLUE                    1018
#define IDC_DARKGREEN                   1019
#define IDC_LIGHTRED                    1020
#define IDC_LIGHTBLUE                   1021
#define IDC_VERSION                     1023
#define IDC_THICKNESS                   1023
#define IDC_ZOOMFACTOR                  1024
#define IDC_SPINTHICK                   1026
#define IDC_SPINZOOM                    1027
#define IDC_SPINDELAY                   1028
#define IDC_PPTOOL_REMOVE               1029
#define IDC_RESTRICTZOOM                1029
#define IDC_CALLFRAMETHICK              1030
#define IDC_LIGHTGREEN                  1031
#define IDC_CALLFRAMETHICKSPIN          1033
#define IDC_PPTOOL_IMAGES               1039
#define IDC_PPTOOL_TOOLBAR              1040
#define IDC_PPTOOL_BEFORE               1041
#define IDC_PPTOOL_AFTER                1042
#define IDC_PPTOOL_SMALL                1050
#define IDC_PPTOOL_MEDIUM               1051
#define IDC_PPTOOL_LARGE                1052
#define IDC_PPTOOL_TOP                  1053
#define IDC_PPTOOL_BOTTOM               1054
#define IDC_PPTOOL_LEFT                 1055
#define IDC_PPTOOL_RIGHT                1056
#define IDC_CALLOUT                     1065
#define IDC_CALLOUTFRAME                1066
#define IDC_LIGHTPENRECT                1067
#define IDC_CALLOUTHANDLE               1067
#define IDC_BITONAL                     1068
#define IDC_ANNTOOL                     1095
#define IDC_CHANGEFONT                  1096
#define IDC_FONTNAME                    1097
#define ID_AT_ZOOM                      32768
#define ID_AT_CALLOUT                   32769
#define IDS_TMXML_ATTACHFAILED          32770
#define IDS_TMXML_CLSIDFAILED           32771
#define IDS_TMXML_XMLNOTATTACHED        32772
#define IDS_TMXML_XMLLOADFAILED         32773
#define IDS_TMXML_NODELISTFAILED        32774
#define IDS_TMXML_DOCUMENT_CHILDREN     32774
#define IDS_TMXML_DOWNLOADFAILED        32775
#define IDS_TMXML_NOATTRIBUTES          32776
#define IDS_TMXML_INVALIDROOTNODE       32777
#define IDS_TMXML_DOCUMENT_NODE         32777
#define IDS_TMXML_ROOT_NODE             32777
#define IDS_TMXML_NOTREENAME            32778
#define IDS_TMXML_TREE_NAME             32778
#define IDS_TMXML_DUPLICATETREE         32779
#define IDS_TMXML_TREE_DUPLICATE        32779
#define IDS_TMXML_TREE_ATTRIBUTE        32780
#define IDS_TMXML_NOMEDIAID             32781
#define IDS_TMXML_MEDIA_ID              32781
#define IDS_TMXML_DUPLICATEMEDIA        32782
#define IDS_TMXML_MEDIA_DUPLICATE       32782
#define IDS_TMXML_MEDIA_ATTRIBUTE       32783
#define IDS_TMXML_NOPAGEID              32784
#define IDS_TMXML_PAGE_ID               32784
#define IDS_TMXML_DUPLICATEPAGE         32785
#define IDS_TMXML_PAGE_DUPLICATE        32785
#define IDS_TMXML_TREATMENT_ATTRIBUTE   32786
#define IDS_TMXML_PAGE_ATTRIBUTE        32787
#define IDS_TMXML_TREATMENT_SOURCE      32788
#define IDS_TMXML_PAGE_SOURCE           32789
#define IDS_TMXML_PAGE_TYPE             32790
#define IDS_TMXML_ATTACH_REQUEST        32791
#define IDS_TMXML_REQUEST_NOTFOUND      32792
#define IDS_TMXML_REQUEST_ERROR         32793
#define IDS_TMXML_NO_ROOT               32794
#define IDS_TMXML_ACTIONS_NODE          32795
#define IDS_TMXML_ACTION_ATTRIBUTE      32796
#define IDS_TMXML_ACTION_NO_COMMAND     32797
#define IDS_TMXML_ACTION_NO_TREE        32798
#define IDS_TMXML_ACTION_BAD_COMMAND    32799
#define IDS_TMXML_PROCESS_NO_TREES      32800
#define IDS_TMXML_PROCESS_VIEW_TREE     32801
#define IDS_TMXML_PROCESS_PRINT_TREE    32802
#define IDS_TMXML_PROCESS_VIEW_PAGE     32803
#define IDS_TMXML_PROCESS_PRINT_PAGE    32804
#define IDS_TMXML_RESPONSE_HEADERS      32805
#define IDS_TMXML_SETTINGS_NODE         32806
#define IDS_TMXML_SETTINGS_MULTIPLE     32807
#define IDS_TMXML_SETTING_ATTRIBUTE     32808
#define IDS_TMXML_SETTINGS_VERSION      32809
#define IDS_TMXML_PROCESS_NO_PRINTER    32810
#define IDS_TMXML_BATCH_NOT_READY       32810
#define IDS_TMXML_ACTION_PRINT_PAGE     32811
#define IDS_TMXML_PROCESS_PRINT_TEMPLATES 32812
#define IDS_PROMPT_PRINT_TREE           32813
#define IDS_TMXML_INVALID_CELL          32815
#define IDS_TMXML_EXPLORER_FAILED       32816
#define IDS_TMXML_NO_TREATMENT_ASP      32817
#define IDS_TMXML_SESSION_FAILED        32818
#define IDS_TMXML_PARSEURL_FAILED       32819
#define IDS_TMXML_PUTTREATMENT_NO_ELEMENT 32820
#define IDS_TMXML_PUT_TREATMENT_NO_ELEMENT 32820
#define IDS_TMXML_PUTTREATMENT_NO_DATABASE 32821
#define IDS_TMXML_PUT_TREATMENT_NO_DATABASE 32821
#define IDS_TMXML_PUTTREATMENT_ASP_NOT_FOUND 32822
#define IDS_TMXML_PUT_TREATMENT_ASP_NOT_FOUND 32822
#define IDS_TMXML_PUTTREATMENT_INVALID_PAGEID 32823
#define IDS_TMXML_PUT_TREATMENT_INVALID_PAGEID 32823
#define IDS_TMXML_PUTTREATMENT_PAGE_NOT_FOUND 32824
#define IDS_TMXML_PUT_TREATMENT_PAGE_NOT_FOUND 32824
#define IDS_TMXML_PUTTREATMENT_NO_PAGE  32825
#define IDS_TMXML_PUT_TREATMENT_NO_PAGE 32825
#define IDS_TMXML_TREATMENT_ID          32826
#define IDS_TMXML_PUT_TREATMENT_INVALID_TREATMENTID 32827
#define IDS_TMXML_PUT_TREATMENT_TREATMENT_NOT_FOUND 32828
#define IDS_TMXML_DELETE_TREATMENT_NO_DATABASE 32829
#define IDS_TMXML_DELETE_TREATMENT_ASP_NOT_FOUND 32830
#define IDS_TMXML_DELETE_TREATMENT_BAD_REQUEST 32831
#define IDS_TMXML_DELETE_TREATMENT_OBJECT_NOT_FOUND 32832
#define IDS_TMXML_PRINT_TREATMENTS      32833
#define IDS_SELECT_INVALID_RANGE        32834
#define IDS_SELECT_NO_PAGES             32835
#define IDS_TMXML_CONNECTION_FAILED     32836
#define IDS_TMXML_OPEN_REQUEST_FAILED   32837
#define IDS_TMXML_SEND_REQUEST_FAILED   32838
#define IDS_TMXML_JUMP_PAGE_FAILED      32839
#define IDS_TMXML_FIND_PAGE_FAILED      32840

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32770
#define _APS_NEXT_CONTROL_VALUE         269
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
