//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D:\TrialMax-Hussain\TrialMax\sourcecode\Trialmax\TmaxPresentation\Tmtool\Tm_tool6.rc
//
#define IDS_TMTOOL                      1
#define IDD_ABOUTBOX_TMTOOL             1
#define IDB_TMTOOL                      1
#define IDI_ABOUTDLL                    1
#define IDS_TMTOOL_PPG                  2
#define IDS_TMTB_NUDGELEFT              3
#define IDS_STRING4                     4
#define IDS_TMTB_NUDGERIGHT             4
#define IDS_TMTB_SAVENUDGE              5
#define IDS_TMTB_ADJUSTABLECALLOUT      6
#define IDS_TMTOOL_PPG_CAPTION          200
#define IDD_PROPPAGE_TMTOOL             200
#define IDB_TOOLBAR                     201
#define IDS_TMTB_CREATEBARFAILED        201
#define IDC_CONFIGURE_TOOLTIPS          201
#define IDB_TBLARGE                     202
#define IDS_TMTB_BUTTONNOTFOUND         202
#define IDC_CONFIGURE                   202
#define IDB_TBMEDIUM                    203
#define IDS_TMTB_NOTINITIALIZED         203
#define IDC_CONFIGURE_RIGHT             203
#define IDB_TBSMALL                     204
#define IDS_TMTB_INVALIDBUTTONID        204
#define IDC_CONFIGURE_TOP               204
#define IDB_TBDLARGE                    205
#define IDS_TMTB_RETRIEVE               205
#define IDS_TMTB_FIRSTZAP               205
#define IDC_CONFIGURE_BOTTOM            205
#define IDB_TBDSMALL                    206
#define IDS_TMTB_BLANK                  206
#define IDS_TMTB_NEXTZAP                206
#define IDC_CONFIGURE_SMALL             206
#define IDB_TBDMEDIUM                   207
#define IDS_TMTB_BLUE                   207
#define IDC_CONFIGURE_MEDIUM            207
#define IDS_TMTB_CALLOUT                208
#define IDC_CONFIGURE_LARGE             208
#define IDB_BITMAP1                     208
#define IDB_COLORTBLARGE                208
#define IDS_TMTB_CCW                    209
#define IDS_TMTB_ROTATECCW              209
#define IDS_TMTB_CLEAR                  210
#define IDS_TMTB_CW                     211
#define IDS_TMTB_ROTATECW               211
#define IDC_ROWS                        211
#define IDS_TMTB_DRAG                   212
#define IDS_TMTB_PAN                    212
#define IDS_TMTB_DRAW                   213
#define IDS_TMTB_DRAWTOOL               213
#define IDS_TMTB_ERASE                  214
#define IDS_TMTB_EXIT                   215
#define IDS_TMTB_GREEN                  216
#define IDS_TMTB_HIGHLIGHT              217
#define IDS_TMTB_NEXT                   218
#define IDS_TMTB_NEXTPAGE               218
#define IDS_TMTB_NORMAL                 219
#define IDS_TMTB_PAUSE                  220
#define IDS_TMTB_PAUSEMOVIE             220
#define IDS_TMTB_PLAY                   221
#define IDS_TMTB_PLAYMOVIE              221
#define IDS_TMTB_PREVIOUS               222
#define IDS_TMTB_PREVPAGE               222
#define IDS_TMTB_RED                    223
#define IDS_TMTB_REDACT                 224
#define IDS_TMTB_REWIND                 225
#define IDS_TMTB_BACKMOVIE              225
#define IDS_TMTB_SAVE                   226
#define IDS_TMTB_SAVEZAP                226
#define IDS_TMTB_SINGLE                 227
#define IDS_TMTB_SINGLEPANE             227
#define IDS_TMTB_SPLITHORIZONTAL        227
#define IDS_TMTB_SPLIT                  228
#define IDS_TMTB_SPLITPANE              228
#define IDS_TMTB_SPLITVERTICAL          228
#define IDS_TMTB_TOOLS                  229
#define IDS_TMTB_CONFIG                 229
#define IDS_TMTB_WIDE                   230
#define IDS_TMTB_ZOOMWIDTH              230
#define IDS_TMTB_YELLOW                 231
#define IDS_TMTB_ZOOM                   232
#define IDS_TMTB_PRINT                  233
#define IDS_TMTB_PREVZAP                234
#define IDS_TMTB_LASTZAP                235
#define IDS_TMTB_CASEMGR                236
#define IDS_TMTB_MANAGER                236
#define IDS_TMTB_STARTMOVIE             237
#define IDS_TMTB_ENDMOVIE               238
#define IDS_TMTB_FWDMOVIE               239
#define IDS_TMTB_FIRSTDESG              240
#define IDS_TMTB_FIRSTDESIGNATION       240
#define IDS_TMTB_LASTDESG               241
#define IDS_TMTB_LASTDESIGNATION        241
#define IDS_TMTB_NEXTDESG               242
#define IDS_TMTB_NEXTDESIGNATION        242
#define IDS_TMTB_PREVDESG               243
#define IDS_TMTB_PREVDESIGNATION        243
#define IDS_TMTB_BACKDESG               244
#define IDS_TMTB_BACKDESIGNATION        244
#define IDS_TMTB_FWDDESG                245
#define IDS_TMTB_FWDDESIGNATION         245
#define IDS_TMTB_STARTDESG              246
#define IDS_TMTB_STARTDESIGNATION       246
#define IDS_TMTB_CONFIGTOOLBARS         247
#define IDS_TMTB_DISABLELINKS           248
#define IDS_TMTB_BLACK                  249
#define IDS_TMTB_WHITE                  250
#define IDS_TMTB_ENABLELINKS            251
#define IDS_TMTB_PAUSEDESIGNATION       252
#define IDS_TMTB_PLAYDESIGNATION        253
#define IDS_TMTB_FIRSTPAGE              254
#define IDS_TMTB_LASTPAGE               255
#define IDS_TMTB_PLAYTHROUGH            256
#define IDS_TMTB_DELETELAST             257
#define IDS_TMTB_DELETEANN              257
#define IDS_TMTB_DELETESELECTIONS       258
#define IDS_TMTB_CUEPGLNNEXT            259
#define IDS_TMTB_CUEPGLNCURRENT         260
#define IDS_TMTB_SELECT                 261
#define IDS_TMTB_FILLEDRECTANGLE        262
#define IDS_TMTB_FILLEDELLIPSE          263
#define IDS_TMTB_ELLIPSE                264
#define IDS_TMTB_RECTANGLE              265
#define IDS_TMTB_ARROW                  266
#define IDS_TMTB_LINE                   267
#define IDS_TMTB_FREEHAND               268
#define IDS_TMTB_SELECTTOOL             269
#define IDS_TMTB_TEXT                   270
#define IDS_TMTB_FULLSCREEN             271
#define IDS_TMTB_STATUSBAR              272
#define IDS_TMTB_DARKRED                273
#define IDS_TMTB_DARKGREEN              274
#define IDS_TMTB_DARKBLUE               275
#define IDS_TMTB_LIGHTRED               276
#define IDS_TMTB_LIGHTGREEN             277
#define IDS_TMTB_LIGHTBLUE              278
#define IDS_TMTB_POLYLINE               279
#define IDS_TMTB_POLYGON                280
#define IDS_TMTB_ANNTEXT                281
#define IDS_TMTB_NOFILE                 282
#define IDS_TMTB_UPDATEZAP              283
#define IDS_TMTB_DELETEZAP              284
#define IDS_TMTB_ZOOMRECTANGLE          285
#define IDS_TMTB_ZOOMMODE               285
#define IDS_TMTB_ZOOMRESTRICTED         285
#define IDS_TMTB_SHADEDCALLOUTS         286
#define IDS_TMTB_SAVESPLITZAP           287
#define IDS_TMTB_GESTUREPAN             288
#define IDS_TMTB_BINDERLIST             289
#define IDD_CONFIGURE_TMTOOL            336
#define IDB_TBTINY                      337
#define IDC_CONFIGURE_REMOVE            1029
#define IDC_CONFIGURE_STRETCH           1037
#define IDC_CONFIGURE_FLAT              1038
#define IDC_CONFIGURE_IMAGES            1039
#define IDC_CONFIGURE_TOOLBAR           1040
#define IDC_CONFIGURE_BEFORE            1041
#define IDC_CONFIGURE_AFTER             1042

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        209
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         212
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
