#if !defined(AFX_TMBROWSE_H__C7786A7D_EC83_4835_BC0E_8C142DAD0B86__INCLUDED_)
#define AFX_TMBROWSE_H__C7786A7D_EC83_4835_BC0E_8C142DAD0B86__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTMBrowse wrapper class

class CTMBrowse : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTMBrowse)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1b964711, 0x19a0, 0x4696, { 0x94, 0x89, 0x0, 0x88, 0x29, 0xd8, 0x7d, 0x7e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetAutoInit();
	void SetAutoInit(BOOL);
	short GetVerBuild();
	void SetVerBuild(short);
	BOOL GetEnableErrors();
	void SetEnableErrors(BOOL);
	short GetVerMajor();
	void SetVerMajor(short);
	short GetVerMinor();
	void SetVerMinor(short);
	CString GetVerTextLong();
	void SetVerTextLong(LPCTSTR);
	CString GetIniFile();
	void SetIniFile(LPCTSTR);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	short GetBorderStyle();
	void SetBorderStyle(short);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	CString GetFilename();
	void SetFilename(LPCTSTR);
	short GetVerQEF();
	void SetVerQEF(short);
	CString GetVerTextShort();
	void SetVerTextShort(LPCTSTR);
	CString GetVerBuildDate();
	void SetVerBuildDate(LPCTSTR);

// Operations
public:
	CString GetRegisteredPath();
	CString GetClassIdString();
	short Initialize();
	short Load(LPCTSTR lpszFilename);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TMBROWSE_H__C7786A7D_EC83_4835_BC0E_8C142DAD0B86__INCLUDED_)
