#if !defined(AFX_TMPRINT_H__B373B22A_B5F2_4F4E_B88D_BD9531B3A9CF__INCLUDED_)
#define AFX_TMPRINT_H__B373B22A_B5F2_4F4E_B88D_BD9531B3A9CF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTMPrint wrapper class

class CTMPrint : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTMPrint)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2b6165a5, 0xc1fc, 0x463e, { 0x9b, 0x56, 0x20, 0x14, 0x3b, 0xf4, 0xf6, 0x27 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	BOOL GetAutoInit();
	void SetAutoInit(BOOL);
	short GetVerBuild();
	void SetVerBuild(short);
	BOOL GetEnableErrors();
	void SetEnableErrors(BOOL);
	short GetVerMajor();
	void SetVerMajor(short);
	short GetVerMinor();
	void SetVerMinor(short);
	CString GetVerTextLong();
	void SetVerTextLong(LPCTSTR);
	CString GetIniFile();
	void SetIniFile(LPCTSTR);
	CString GetIniSection();
	void SetIniSection(LPCTSTR);
	BOOL GetEnablePowerPoint();
	void SetEnablePowerPoint(BOOL);
	BOOL GetCollate();
	void SetCollate(BOOL);
	short GetCopies();
	void SetCopies(short);
	BOOL GetIncludePathInFileName();
	void SetIncludePathInFileName(BOOL);
	BOOL GetIncludePageTotal();
	void SetIncludePageTotal(BOOL);
	BOOL GetPrintImage();
	void SetPrintImage(BOOL);
	BOOL GetPrintBarcodeGraphic();
	void SetPrintBarcodeGraphic(BOOL);
	BOOL GetPrintBarcodeText();
	void SetPrintBarcodeText(BOOL);
	BOOL GetPrintName();
	void SetPrintName(BOOL);
	BOOL GetPrintFileName();
	void SetPrintFileName(BOOL);
	BOOL GetPrintDeponent();
	void SetPrintDeponent(BOOL);
	BOOL GetPrintPageNumber();
	void SetPrintPageNumber(BOOL);
	BOOL GetPrintCellBorder();
	void SetPrintCellBorder(BOOL);
	CString GetPrinter();
	void SetPrinter(LPCTSTR);
	CString GetTemplateName();
	void SetTemplateName(LPCTSTR);
	BOOL GetForceNewPage();
	void SetForceNewPage(BOOL);
	BOOL GetUseSlideIDs();
	void SetUseSlideIDs(BOOL);
	CString GetBarcodeCharacter();
	void SetBarcodeCharacter(LPCTSTR);
	BOOL GetShowOptions();
	void SetShowOptions(BOOL);
	CString GetBarcodeFont();
	void SetBarcodeFont(LPCTSTR);
	BOOL GetShowStatus();
	void SetShowStatus(BOOL);
	float GetLeftMargin();
	void SetLeftMargin(float);
	float GetTopMargin();
	void SetTopMargin(float);
	BOOL GetPrintCalloutBorders();
	void SetPrintCalloutBorders(BOOL);
	unsigned long GetPrintBorderColor();
	void SetPrintBorderColor(unsigned long);
	float GetPrintBorderThickness();
	void SetPrintBorderThickness(float);
	BOOL GetPrintCallouts();
	void SetPrintCallouts(BOOL);
	BOOL GetAutoRotate();
	void SetAutoRotate(BOOL);
	BOOL GetPrintForeignBarcode();
	void SetPrintForeignBarcode(BOOL);
	BOOL GetEnableAxErrors();
	void SetEnableAxErrors(BOOL);
	short GetVerQEF();
	void SetVerQEF(short);
	CString GetVerTextShort();
	void SetVerTextShort(LPCTSTR);
	CString GetVerBuildDate();
	void SetVerBuildDate(LPCTSTR);
	CString GetJobName();
	void SetJobName(LPCTSTR);
	BOOL GetPrintSourceBarcode();
	void SetPrintSourceBarcode(BOOL);
	BOOL GetInsertSlipSheet();
	void SetInsertSlipSheet(BOOL);
	short GetCalloutFrameColor();
	void SetCalloutFrameColor(short);

// Operations
public:
	short Initialize();
	short Add(LPCTSTR lpszString);
	long GetQueueCount();
	short Clear();
	short RefreshTemplates();
	short Print();
	short EnumerateTemplates();
	short EnumeratePrinters();
	CString GetDefaultPrinter();
	short SelectPrinter();
	short SetPrintTemplates(long lTemplates);
	short SetPrintTemplate(long lTemplate);
	BOOL IsReady();
	CString GetRegisteredPath();
	CString GetClassIdString();
	long GetPrintTemplates();
	long GetPrintTemplate();
	short GetRowsPerPage();
	short GetColumnsPerPage();
	short Abort();
	long GetFieldEnabledMask(LPCTSTR lpszTemplate);
	long GetFieldDefaultMask(LPCTSTR lpszTemplate);
	BOOL SetPrinterProperties(long hWnd);
	short ShowPrinterCaps();
	void EnableDIBPrinting(short bEnable);
	short EnumerateTextFields(LPCTSTR lpszTemplate);
	short SetTextFieldEnabled(long lId, LPCTSTR lpszName, short bEnabled);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TMPRINT_H__B373B22A_B5F2_4F4E_B88D_BD9531B3A9CF__INCLUDED_)
