#if !defined(AFX_TMSETUP_H__847B5A7C_C117_4F5E_AF47_7743CA21F63D__INCLUDED_)
#define AFX_TMSETUP_H__847B5A7C_C117_4F5E_AF47_7743CA21F63D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTMSetup wrapper class

class CTMSetup : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTMSetup)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xb581682e, 0x5cc0, 0x4e50, { 0xbb, 0xbc, 0x58, 0x2d, 0x78, 0x67, 0x7e, 0x5a } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetAutoInit();
	void SetAutoInit(BOOL);
	CString GetIniFile();
	void SetIniFile(LPCTSTR);
	BOOL GetEnableErrors();
	void SetEnableErrors(BOOL);
	short GetVerMajor();
	void SetVerMajor(short);
	short GetVerMinor();
	void SetVerMinor(short);
	CString GetVerTextLong();
	void SetVerTextLong(LPCTSTR);
	short GetVerBuild();
	void SetVerBuild(short);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	BOOL GetAboutPage();
	void SetAboutPage(BOOL);
	BOOL GetDatabasePage();
	void SetDatabasePage(BOOL);
	BOOL GetDirectXPage();
	void SetDirectXPage(BOOL);
	BOOL GetDiagnosticPage();
	void SetDiagnosticPage(BOOL);
	BOOL GetGraphicsPage();
	void SetGraphicsPage(BOOL);
	BOOL GetSystemPage();
	void SetSystemPage(BOOL);
	BOOL GetTextPage();
	void SetTextPage(BOOL);
	BOOL GetVideoPage();
	void SetVideoPage(BOOL);
	CString GetAboutName();
	void SetAboutName(LPCTSTR);
	CString GetAboutVersion();
	void SetAboutVersion(LPCTSTR);
	CString GetAboutCopyright();
	void SetAboutCopyright(LPCTSTR);
	CString GetAboutPhone();
	void SetAboutPhone(LPCTSTR);
	CString GetAboutEmail();
	void SetAboutEmail(LPCTSTR);
	BOOL GetCapturePage();
	void SetCapturePage(BOOL);
	BOOL GetRingtailPage();
	void SetRingtailPage(BOOL);
	BOOL GetEnableAxErrors();
	void SetEnableAxErrors(BOOL);
	short GetVerQEF();
	void SetVerQEF(short);
	CString GetVerTextShort();
	void SetVerTextShort(LPCTSTR);
	CString GetVerBuildDate();
	void SetVerBuildDate(LPCTSTR);
	CString GetPresentationFileSpec();
	void SetPresentationFileSpec(LPCTSTR);

// Operations
public:
	short Initialize();
	short Save();
	short SetActiveFilters(LPCTSTR lpFilters, LPUNKNOWN lpMediaControl);
	CString GetClassIdString();
	CString GetRegisteredPath();
	void EnumAxVersions();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TMSETUP_H__847B5A7C_C117_4F5E_AF47_7743CA21F63D__INCLUDED_)
