//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tmaxdemo.rc
//
#define IDD_CONFIRMVIDEOS               129
#define IDI_QUESTIONMARK                130
#define IDD_CONFIRMDB                   130
#define IDC_VIDEODRIVE                  1002
#define IDC_DRIVE                       1003
#define IDC_COMMENT                     1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
