#ifdef APSTUDIO_INVOKED
#define APSTUDIO_READONLY_SYMBOLS
#define APSTUDIO_HIDDEN_SYMBOLS
#endif

#define IDS_FIRST_TMDB					10000

#define IDS_TMDB_FILENOTFOUND			(IDS_FIRST_TMDB + 1)
#define IDS_TMDB_OPENDBFAILED			(IDS_FIRST_TMDB + 2)
#define IDS_TMDB_OPENRSFAILED			(IDS_FIRST_TMDB + 3)
#define IDS_TMDB_MEMERROR				(IDS_FIRST_TMDB + 4)
#define IDS_TMDB_INVALIDRECORDSET		(IDS_FIRST_TMDB + 5)
#define IDS_TMDB_DBNOTOPEN				(IDS_FIRST_TMDB + 6)
#define IDS_TMDB_NOVERSIONINFO			(IDS_FIRST_TMDB + 7)
#define IDS_TMDB_INVALIDPARAM			(IDS_FIRST_TMDB + 8)
#define IDS_TMDB_INVALIDVERSION			(IDS_FIRST_TMDB + 9)
#define IDS_TMDB_VERSIONMATCH			(IDS_FIRST_TMDB + 10)
#define IDS_TMDB_ALIASNOTFOUND			(IDS_FIRST_TMDB + 11)
#define IDS_TMDB_NOALIASNODE			(IDS_FIRST_TMDB + 12)
#define IDS_TMDB_NOCASEOPTIONS			(IDS_FIRST_TMDB + 13)
#define IDS_TMDB_CREATECASEOPTIONS		(IDS_FIRST_TMDB + 14)
#define IDS_TMDB_LOADCASEOPTIONS		(IDS_FIRST_TMDB + 15)
#define IDS_TMDB_NOCASEPATHNODE			(IDS_FIRST_TMDB + 16)
#define IDS_TMDB_BADCASEPATHNODE		(IDS_FIRST_TMDB + 17)
#define IDS_TMDB_NOMACHINENAME			(IDS_FIRST_TMDB + 18)
#define IDS_TMDB_NOMACHINENODE			(IDS_FIRST_TMDB + 19)
#define IDS_TMDB_BADMACHINENODE			(IDS_FIRST_TMDB + 20)
#define IDS_TMDB_NOPATHMAPNODE			(IDS_FIRST_TMDB + 21)
#define IDS_TMDB_NOTRANSCRIPTRECORD		(IDS_FIRST_TMDB + 22)
#define IDS_TMDB_NOSEGMENTS				(IDS_FIRST_TMDB + 23)
#define IDS_TMDB_NOSEGMENTVIDEO			(IDS_FIRST_TMDB + 24)

#ifdef APSTUDIO_INVOKED
#undef APSTUDIO_HIDDEN_SYMBOLS
#undef APSTUDIO_READONLY_SYMBOLS
#endif

