/*************************************************************
   LTUnlock.H - support unlock macro defines
   Copyright (c) 1991-2007 LEAD Technologies, Inc.
   All Rights Reserved.
*************************************************************/

#if !defined(LTUNLOCK_H)
#define LTUNLOCK_H

#include "Ltkey.h"

#if defined(LEADTOOLS_V16_OR_LATER)
#define UNLOCKSUPPORT() \
{ \
   L_UnlockSupport(L_SUPPORT_DOCUMENT, L_KEY_DOCUMENT); \
   L_UnlockSupport(L_SUPPORT_OCR, L_KEY_OCR); \
   L_UnlockSupport(L_SUPPORT_MEDICAL, L_KEY_MEDICAL); \
   L_UnlockSupport(L_SUPPORT_MEDICAL_NET, L_KEY_MEDICAL_NET); \
   L_UnlockSupport(L_SUPPORT_BARCODES_1D, L_KEY_BARCODES_1D); \
   L_UnlockSupport(L_SUPPORT_BARCODES_2D_READ, L_KEY_BARCODES_2D_READ); \
   L_UnlockSupport(L_SUPPORT_BARCODES_2D_WRITE, L_KEY_BARCODES_2D_WRITE); \
   L_UnlockSupport(L_SUPPORT_BARCODES_PDF_READ, L_KEY_BARCODES_PDF_READ); \
   L_UnlockSupport(L_SUPPORT_BARCODES_PDF_WRITE, L_KEY_BARCODES_PDF_WRITE); \
   L_UnlockSupport(L_SUPPORT_VECTOR, L_KEY_VECTOR); \
   L_UnlockSupport(L_SUPPORT_PDF, L_KEY_PDF);\
   L_UnlockSupport(L_SUPPORT_J2K, L_KEY_J2K);\
   L_UnlockSupport(L_SUPPORT_CMW, L_KEY_CMW);\
   L_UnlockSupport(L_SUPPORT_DICOM, L_KEY_DICOM);\
   L_UnlockSupport(L_SUPPORT_EXTGRAY, L_KEY_EXTGRAY);\
   L_UnlockSupport(L_SUPPORT_BITONAL, L_KEY_BITONAL);\
   L_UnlockSupport(L_SUPPORT_PDF_SAVE, L_KEY_PDF_SAVE);\
   L_UnlockSupport(L_SUPPORT_OCR_PDF_OUTPUT, L_KEY_OCR_PDF_OUTPUT);\
   L_UnlockSupport(L_SUPPORT_BARCODES_DATAMATRIX_READ, L_KEY_BARCODES_DATAMATRIX_READ); \
   L_UnlockSupport(L_SUPPORT_BARCODES_DATAMATRIX_WRITE, L_KEY_BARCODES_DATAMATRIX_WRITE); \
   L_UnlockSupport(L_SUPPORT_LTPRO, L_KEY_LTPRO); \
   L_UnlockSupport(L_SUPPORT_OCR_PROFESSIONAL_ASIAN, L_KEY_OCR_PROFESSIONAL_ASIAN); \
   L_UnlockSupport(L_SUPPORT_ICR, L_KEY_ICR); \
   L_UnlockSupport(L_SUPPORT_OMR, L_KEY_OMR); \
   L_UnlockSupport(L_SUPPORT_ABC, L_KEY_ABC);\
   L_UnlockSupport(L_SUPPORT_BARCODES_QR_READ, L_KEY_BARCODES_QR_READ); \
   L_UnlockSupport(L_SUPPORT_BARCODES_QR_WRITE, L_KEY_BARCODES_QR_WRITE); \
   L_UnlockSupport(L_SUPPORT_BARCODES_1D_SILVER, L_KEY_BARCODES_1D_SILVER); \
   L_UnlockSupport(L_SUPPORT_MOBILE, L_KEY_MOBILE); \
   L_UnlockSupport(L_SUPPORT_JBIG2, L_KEY_JBIG2); \
   L_UnlockSupport(L_SUPPORT_ABIC_READ, L_KEY_ABIC_READ); \
   L_UnlockSupport(L_SUPPORT_ABIC_SAVE, L_KEY_ABIC_SAVE); \
   L_UnlockSupport(L_SUPPORT_PDF_READ, L_KEY_PDF_READ);\
   L_UnlockSupport(L_SUPPORT_PDF_ADVANCED, L_KEY_PDF_ADVANCED);\
   L_UnlockSupport(L_SUPPORT_NITF, L_KEY_NITF);\
   L_UnlockSupport(L_SUPPORT_OCR_ARABIC, L_KEY_OCR_ARABIC); \
   L_UnlockSupport(L_SUPPORT_JPIP, L_KEY_JPIP); \
   L_UnlockSupport(L_SUPPORT_OCR_PLUS, L_KEY_OCR_PLUS); \
   L_UnlockSupport(L_SUPPORT_OCR_PLUS_PDF_OUTPUT, L_KEY_OCR_PLUS_PDF_OUTPUT); \
   L_UnlockSupport(L_SUPPORT_ICR_PLUS, L_KEY_ICR_PLUS); \
   L_UnlockSupport(L_SUPPORT_OMR_PLUS, L_KEY_OMR_PLUS); \
   L_UnlockSupport(L_SUPPORT_OCR_PLUS_PDF_LEAD_OUTPUT, L_KEY_OCR_PLUS_PDF_LEAD_OUTPUT); \
   L_UnlockSupport(L_SUPPORT_OCR_PROFESSIONAL, L_KEY_OCR_PROFESSIONAL); \
   L_UnlockSupport(L_SUPPORT_OCR_PROFESSIONAL_PDF_OUTPUT, L_KEY_OCR_PROFESSIONAL_PDF_OUTPUT); \
   L_UnlockSupport(L_SUPPORT_ICR_PROFESSIONAL, L_KEY_ICR_PROFESSIONAL); \
   L_UnlockSupport(L_SUPPORT_OMR_PROFESSIONAL, L_KEY_OMR_PROFESSIONAL); \
   L_UnlockSupport(L_SUPPORT_OCR_PROFESSIONAL_PDF_LEAD_OUTPUT, L_KEY_OCR_PROFESSIONAL_PDF_LEAD_OUTPUT); \
   L_UnlockSupport(L_SUPPORT_OCR_ADVANTAGE, L_KEY_OCR_ADVANTAGE); \
   L_UnlockSupport(L_SUPPORT_OCR_ADVANTAGE_PDF_LEAD_OUTPUT, L_KEY_OCR_ADVANTAGE_PDF_LEAD_OUTPUT); \
   L_UnlockSupport(L_SUPPORT_FORMS, L_KEY_FORMS); \
   L_UnlockSupport(L_SUPPORT_MEDICAL_SERVER, L_KEY_MEDICAL_SERVER); \
   L_UnlockSupport(L_SUPPORT_PRINT_DRIVER, L_KEY_PRINT_DRIVER); \
   L_UnlockSupport(L_SUPPORT_DOCUMENT_WRITERS, L_KEY_DOCUMENT_WRITERS); \
   L_UnlockSupport(L_SUPPORT_LEAD_OMR, L_KEY_LEAD_OMR); \
   L_UnlockSupport(L_SUPPORT_MEDIA_WRITER, L_KEY_MEDIA_WRITER); \
   L_UnlockSupport(L_SUPPORT_DOCUMENT_WRITERS_PDF, L_KEY_DOCUMENT_WRITERS_PDF); \
   L_UnlockSupport(L_SUPPORT_MEDICAL_3D, L_KEY_MEDICAL_3D); \
   L_UnlockSupport(L_SUPPORT_OCR_ARABIC_PDF_LEAD_OUTPUT, L_KEY_OCR_ARABIC_PDF_LEAD_OUTPUT); \
   L_UnlockSupport(L_SUPPORT_PRINT_DRIVER_SERVER, L_KEY_PRINT_DRIVER_SERVER); \
}
#else
#define UNLOCKSUPPORT() \
{ \
   L_UnlockSupport(L_SUPPORT_DOCUMENT, L_KEY_DOCUMENT); \
   L_UnlockSupport(L_SUPPORT_OCR, L_KEY_OCR); \
   L_UnlockSupport(L_SUPPORT_MEDICAL, L_KEY_MEDICAL); \
   L_UnlockSupport(L_SUPPORT_MEDICAL_NET, L_KEY_MEDICAL_NET); \
   L_UnlockSupport(L_SUPPORT_BARCODES_1D, L_KEY_BARCODES_1D); \
   L_UnlockSupport(L_SUPPORT_BARCODES_2D_READ, L_KEY_BARCODES_2D_READ); \
   L_UnlockSupport(L_SUPPORT_BARCODES_2D_WRITE, L_KEY_BARCODES_2D_WRITE); \
   L_UnlockSupport(L_SUPPORT_BARCODES_PDF_READ, L_KEY_BARCODES_PDF_READ); \
   L_UnlockSupport(L_SUPPORT_BARCODES_PDF_WRITE, L_KEY_BARCODES_PDF_WRITE); \
   L_UnlockSupport(L_SUPPORT_VECTOR, L_KEY_VECTOR); \
   L_UnlockSupport(L_SUPPORT_PDF, L_KEY_PDF);\
   L_UnlockSupport(L_SUPPORT_J2K, L_KEY_J2K);\
   L_UnlockSupport(L_SUPPORT_CMW, L_KEY_CMW);\
   L_UnlockSupport(L_SUPPORT_DICOM, L_KEY_DICOM);\
   L_UnlockSupport(L_SUPPORT_EXTGRAY, L_KEY_EXTGRAY);\
   L_UnlockSupport(L_SUPPORT_BITONAL, L_KEY_BITONAL);\
   L_UnlockSupport(L_SUPPORT_PDF_SAVE, L_KEY_PDF_SAVE);\
   L_UnlockSupport(L_SUPPORT_OCR_PDF_OUTPUT, L_KEY_OCR_PDF_OUTPUT);\
   L_UnlockSupport(L_SUPPORT_BARCODES_DATAMATRIX_READ, L_KEY_BARCODES_DATAMATRIX_READ); \
   L_UnlockSupport(L_SUPPORT_BARCODES_DATAMATRIX_WRITE, L_KEY_BARCODES_DATAMATRIX_WRITE); \
   L_UnlockSupport(L_SUPPORT_LTPRO, L_KEY_LTPRO); \
   L_UnlockSupport(L_SUPPORT_ICR, L_KEY_ICR); \
   L_UnlockSupport(L_SUPPORT_OMR, L_KEY_OMR); \
   L_UnlockSupport(L_SUPPORT_ABC, L_KEY_ABC);\
   L_UnlockSupport(L_SUPPORT_BARCODES_QR_READ, L_KEY_BARCODES_QR_READ); \
   L_UnlockSupport(L_SUPPORT_BARCODES_QR_WRITE, L_KEY_BARCODES_QR_WRITE); \
   L_UnlockSupport(L_SUPPORT_BARCODES_1D_SILVER, L_KEY_BARCODES_1D_SILVER); \
   L_UnlockSupport(L_SUPPORT_MOBILE, L_KEY_MOBILE); \
   L_UnlockSupport(L_SUPPORT_JBIG2, L_KEY_JBIG2); \
   L_UnlockSupport(L_SUPPORT_ABIC_READ, L_KEY_ABIC_READ); \
   L_UnlockSupport(L_SUPPORT_ABIC_SAVE, L_KEY_ABIC_SAVE); \
   L_UnlockSupport(L_SUPPORT_PDF_READ, L_KEY_PDF_READ);\
   L_UnlockSupport(L_SUPPORT_PDF_ADVANCED, L_KEY_PDF_ADVANCED);\
   L_UnlockSupport(L_SUPPORT_NITF, L_KEY_NITF);\
   L_UnlockSupport(L_SUPPORT_OCR_ARABIC, L_KEY_OCR_ARABIC); \
}
#endif // #if defined(LEADTOOLS_V16_OR_LATER)
#endif // #if !defined(LTUNLOCK_H)
