#if !defined(AFX_TMLPEN_H__A47EA475_EC81_4A67_A9C5_9FF96CE7D936__INCLUDED_)
#define AFX_TMLPEN_H__A47EA475_EC81_4A67_A9C5_9FF96CE7D936__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTMLpen wrapper class

class CTMLpen : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTMLpen)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7efcbdc0, 0xf749, 0x4574, { 0x8d, 0xc1, 0x2e, 0x55, 0x75, 0xdd, 0x98, 0x8 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetVerBuild();
	void SetVerBuild(short);
	short GetVerMajor();
	void SetVerMajor(short);
	short GetVerMinor();
	void SetVerMinor(short);
	BOOL GetAutoInit();
	void SetAutoInit(BOOL);
	BOOL GetEnableErrors();
	void SetEnableErrors(BOOL);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	short GetAppearance();
	void SetAppearance(short);
	short GetBorderStyle();
	void SetBorderStyle(short);
	BOOL GetAlwaysOnTop();
	void SetAlwaysOnTop(BOOL);
	CString GetVerTextLong();
	void SetVerTextLong(LPCTSTR);
	short GetVerQEF();
	void SetVerQEF(short);
	CString GetVerTextShort();
	void SetVerTextShort(LPCTSTR);
	CString GetVerBuildDate();
	void SetVerBuildDate(LPCTSTR);

// Operations
public:
	short Initialize();
	CString GetRegisteredPath();
	CString GetClassIdString();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TMLPEN_H__A47EA475_EC81_4A67_A9C5_9FF96CE7D936__INCLUDED_)
