#if !defined(AFX_TMSHARE_H__49522DE7_F129_4BF5_8791_C24955AADA60__INCLUDED_)
#define AFX_TMSHARE_H__49522DE7_F129_4BF5_8791_C24955AADA60__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTMShare wrapper class

class CTMShare : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTMShare)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xcb5d5073, 0xab77, 0x45f6, { 0xb7, 0x28, 0x18, 0x8, 0xdd, 0xc8, 0x0, 0x26 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetVerBuild();
	void SetVerBuild(short);
	BOOL GetEnableErrors();
	void SetEnableErrors(BOOL);
	short GetVerMajor();
	void SetVerMajor(short);
	short GetVerMinor();
	void SetVerMinor(short);
	CString GetVerTextLong();
	void SetVerTextLong(LPCTSTR);
	short GetOwner();
	void SetOwner(short);
	long GetPeekPeriod();
	void SetPeekPeriod(long);
	long GetCommand();
	void SetCommand(long);
	long GetError();
	void SetError(long);
	CString GetMediaId();
	void SetMediaId(LPCTSTR);
	BOOL GetEnableAxErrors();
	void SetEnableAxErrors(BOOL);
	CString GetBarcode();
	void SetBarcode(LPCTSTR);
	CString GetAppFolder();
	void SetAppFolder(LPCTSTR);
	long GetPrimaryId();
	void SetPrimaryId(long);
	long GetSecondaryId();
	void SetSecondaryId(long);
	long GetTertiaryId();
	void SetTertiaryId(long);
	long GetQuaternaryId();
	void SetQuaternaryId(long);
	CString GetSourceFileName();
	void SetSourceFileName(LPCTSTR);
	CString GetSourceFilePath();
	void SetSourceFilePath(LPCTSTR);
	CString GetCaseFolder();
	void SetCaseFolder(LPCTSTR);
	long GetBarcodeId();
	void SetBarcodeId(long);
	long GetDisplayOrder();
	void SetDisplayOrder(long);
	short GetVerQEF();
	void SetVerQEF(short);
	CString GetVerTextShort();
	void SetVerTextShort(LPCTSTR);
	CString GetVerBuildDate();
	void SetVerBuildDate(LPCTSTR);
	long GetPageNumber();
	void SetPageNumber(long);
	short GetLineNumber();
	void SetLineNumber(short);

// Operations
public:
	CString GetRegisteredPath();
	CString GetClassIdString();
	BOOL GetInitialized();
	short GetResponse();
	short GetRequest();
	short SetResponse();
	void Terminate();
	BOOL IsRunning();
	CString GetSisterFileSpec();
	short Initialize();
	short SetRequest(long lWaitResponse);
	short Execute();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TMSHARE_H__49522DE7_F129_4BF5_8791_C24955AADA60__INCLUDED_)
