//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tmviewvc.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_TMVIEWVC_FORM               101
#define IDD_PROMPT                      102
#define IDD_RECTANGLE                   103
#define IDD_DIAGNOSTICS                 104
#define IDD_SAVE_PAGES                  105
#define IDR_MAINFRAME                   128
#define IDR_TMVIEWTYPE                  129
#define IDD_AUTOROTATE                  131
#define IDC_COLOR                       240
#define IDC_TRANSPARANCY                245
#define IDC_FOLDERS                     564
#define IDC_FILES                       566
#define IDC_TMVIEWCTRL1                 1000
#define IDC_LIST                        1000
#define IDC_TITLE                       1001
#define IDC_VALUE                       1002
#define IDC_ROTATE_FOLDER               1004
#define IDC_ROTATE_FILES                1005
#define IDC_TMVIEW                      1006
#define IDC_SUBFOLDERS                  1007
#define IDC_TIFF                        1008
#define IDC_LEFT                        1008
#define IDC_CLOCKWISE                   1009
#define IDC_TOP                         1009
#define IDC_BACKUP                      1010
#define IDC_RIGHT                       1010
#define IDC_BOTTOM                      1011
#define IDC_LOCKED                      1012
#define IDC_FOLDER                      1014
#define IDC_PREFIX                      1015
#define IDC_CONTROL_ABOUT               32771
#define IDC_VIEW_PROPERTIES             32772
#define ID_VIEW_PROPERTIES              32773
#define ID_CONTROL_ABOUT                32774
#define ID_PROPERTIES_ANNOTATIONS       32775
#define ID_PROPERTIES_SCALEIMAGE        32776
#define ID_PROPERTIES_FITTOIMAGE        32777
#define ID_ACTION_HIGHLIGHT             32778
#define ID_ACTION_REDACT                32779
#define ID_ACTION_ANNOTATE              32780
#define ID_ACTION_ERASE                 32781
#define ID_ACTION_DRAW                  32782
#define ID_ACTION_ZOOM                  32783
#define ID_ACTION_ROTATECW              32784
#define ID_ROTATE_CCW                   32785
#define ID_ACTION_NONE                  32786
#define ID_ACTION_ROTATECCW             32787
#define ID_ACTION_NEXT                  32788
#define ID_ACTION_PREV                  32789
#define ID_ACTION_SELECT                32790
#define ID_ACTION_RESETZOOM             32791
#define ID_ACTION_PLAY                  32792
#define ID_ACTION_CONTINUOUS            32793
#define ID_ACTION_STOP                  32794
#define ID_ACTION_ZOOMWIDTH             32796
#define ID_ACTION_ZOOMHEIGHT            32797
#define ID_FILE_SAVEAS                  32798
#define ID_ACTION_SAVEANN               32799
#define ID_ACTION_LOADANN               32800
#define ID_ACTION_REALIZE               32801
#define ID_PANLEFT                      32805
#define ID_PANRIGHT                     32806
#define ID_PANUP                        32807
#define ID_PANDOWN                      32808
#define ID_PROPERTIES_PANIMAGE          32810
#define ID_CALLOUT                      32811
#define ID_PRINT                        32813
#define ID_ACTION_LOADVIEW              32814
#define ID_ACTION_PRINT                 32815
#define ID_MOUSEPAN                     32816
#define ID_ACTION_LOADSCALED            32820
#define ID_ACTION_VIEWCALLOUTS          32822
#define ID_ACTION_LOADSCALECALL         32823
#define ID_ACTION_LOADVIEWCALL          32824
#define ID_ACTION_PAN                   32827
#define ID_ACTION_PRINTVIEW             32828
#define ID_ACTION_SETPRINTER            32830
#define ID_SPLITSCREEN                  32831
#define ID_FILE_RELOAD                  32832
#define ID_LOADLEFT                     32833
#define ID_LOADRIGHT                    32834
#define ID_LOADACTIVE                   32835
#define ID_SYNCPROPS                    32836
#define ID_PRINT_FULLLEFT               32837
#define ID_PRINT_VISIBLELEFT            32838
#define ID_PRINT_FULLRIGHT              32839
#define ID_PRINT_VISIBLERIGHT           32840
#define ID_PRINT_FULLBOTH               32841
#define ID_PRINT_VISIBLEBOTH            32842
#define ID_PROPERTIES_SYNCCALLANN       32843
#define ID_DELETELAST                   32844
#define ID_DELETESELECTIONS             32845
#define ID_SELECT                       32846
#define ID_PROPERTIES_SELECTOR          32847
#define ID_PROPERTIES_KEEPASPECT        32848
#define ID_PROPERTIES_ZOOMTORECT        32849
#define ID_COPYCLIPBOARD                32850
#define ID_PASTECLIPBOARD               32851
#define ID_IMAGE_INFORMATION            32852
#define ID_PRINTER_DEFAULT              32853
#define ID_PRINTER_SETBYNAME            32854
#define ID_PRINTER_CURRENT              32855
#define ID_DESKEW                       32856
#define ID_DESKEW_BACK_COLOR            32857
#define ID_VIEW_CLASS_ID                32858
#define ID_VIEW_REGISTERED_PATH         32859
#define ID_PROPERTIES_ANNOTATECALLOUTS  32860
#define ID_HOLE_REMOVE                  32861
#define ID_DESPECKLE                    32862
#define ID_DOT_REMOVE                   32863
#define ID_BORDER_REMOVE                32864
#define ID_SMOOTH                       32865
#define ID_CLEANUP                      32866
#define ID_ORIENT_AUTO                  32867
#define ID_ORIENTATION_AUTO             32868
#define ID_ORIENTATION_PORTRAIT         32869
#define ID_ORIENTATION_LANDSCAPE        32870
#define ID_PAGE_SETUP                   32871
#define ID_SPLIT_HORIZONTAL             32872
#define ID_QFACTOR                      32873
#define ID_SHOW_DIAGNOSTICS             32874
#define ID_HIDE_DIAGNOSTICS             32875
#define ID_AUTOROTATE                   32876
#define ID_DRAW_RECTANGLE               32877
#define ID_SOURCE_RECTANGLE             32878
#define ID_VIEW_EVENTS                  32879
#define ID_PRINT_SET_PROPERTIES         32880
#define ID_SAVE_PAGES                   32881
#define ID_PRINTER_CAPS                 32882

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32883
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
