#include "afxdisp.h"
#include "afxctl.h"
#include "tmview.h"

BEGIN_EVENTSINK_MAP(CTMViewCtrl, COleControl)
    //{{AFX_EVENTSINK_MAP(CTMViewCtrl)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 14 /* Animate */, OnAAnimate, VTS_BOOL)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 12 /* AnnChange */, OnAAnnChange, VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 9 /* AnnClicked */, OnAAnnClicked, VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 7 /* AnnCreate */, OnAAnnCreate, VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 8 /* AnnDestroy */, OnAAnnDestroy, VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 10 /* AnnDrawn */, OnAAnnDrawn, VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 31 /* AnnMenu */, OnAAnnMenu, VTS_DISPATCH)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 28 /* AnnMouseDown */, OnAAnnMouseDown, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 29 /* AnnMouseMove */, OnAAnnMouseMove, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 30 /* AnnMouseUp */, OnAAnnMouseUp, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 16 /* AnnSelect */, OnAAnnSelect, VTS_VARIANT VTS_I2)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 38 /* AnnUserMenu */, OnAAnnUserMenu, VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, DISPID_CLICK/* Click */, OnAMouseClick, VTS_NONE)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, DISPID_DBLCLICK /* DblClick */, OnAMouseDblClick, VTS_NONE)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, DISPID_KEYDOWN /* KeyDown */, OnAKeyDown, VTS_PI2 VTS_I2)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, DISPID_KEYPRESS /* KeyPress */, OnAKeyPress, VTS_PI2)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, DISPID_KEYUP /* KeyUp */, OnAKeyUp, VTS_PI2 VTS_I2)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, DISPID_MOUSEDOWN /* MouseDown */, OnAMouseDown, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, DISPID_MOUSEMOVE /* MouseMove */, OnAMouseMove, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, DISPID_MOUSEUP /* MouseUp */, OnAMouseUp, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEA, 15/* RubberBand */, OnARubberBand, VTS_NONE)

	ON_EVENT(CTMViewCtrl, IDC_PANEB, 14 /* Animate */, OnAAnimate, VTS_BOOL)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 12 /* AnnChange */, OnAAnnChange, VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 9 /* AnnClicked */, OnAAnnClicked, VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 7 /* AnnCreate */, OnAAnnCreate, VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 8 /* AnnDestroy */, OnAAnnDestroy, VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 10 /* AnnDrawn */, OnAAnnDrawn, VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 31 /* AnnMenu */, OnAAnnMenu, VTS_DISPATCH)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 28 /* AnnMouseDown */, OnAAnnMouseDown, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 29 /* AnnMouseMove */, OnAAnnMouseMove, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 30 /* AnnMouseUp */, OnAAnnMouseUp, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 16 /* AnnSelect */, OnAAnnSelect, VTS_VARIANT VTS_I2)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 38 /* AnnUserMenu */, OnAAnnUserMenu, VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, DISPID_CLICK/* Click */, OnAMouseClick, VTS_NONE)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, DISPID_DBLCLICK /* DblClick */, OnAMouseDblClick, VTS_NONE)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, DISPID_KEYDOWN /* KeyDown */, OnAKeyDown, VTS_PI2 VTS_I2)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, DISPID_KEYPRESS /* KeyPress */, OnAKeyPress, VTS_PI2)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, DISPID_KEYUP /* KeyUp */, OnAKeyUp, VTS_PI2 VTS_I2)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, DISPID_MOUSEDOWN /* MouseDown */, OnAMouseDown, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, DISPID_MOUSEMOVE /* MouseMove */, OnAMouseMove, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, DISPID_MOUSEUP /* MouseUp */, OnAMouseUp, VTS_I2 VTS_I2 VTS_I4 VTS_I4)
	ON_EVENT(CTMViewCtrl, IDC_PANEB, 15/* RubberBand */, OnARubberBand, VTS_NONE)
	//}}AFX_EVENTSINK_MAP
END_EVENTSINK_MAP()
