//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D:\TrialMax-Hussain\TrialMax\sourcecode\Trialmax\TmaxPresentation\Tmview\Tm_view6.rc
//
#define IDS_TM_VIEW6                    1
#define IDD_ABOUTBOX_TM_VIEW6           1
#define IDB_TM_VIEW6                    1
#define IDI_ABOUTDLL                    1
#define IDD_ANNTEXT                     1
#define IDS_TM_VIEW6_PPG                2
#define IDD_DIAGNOSTICS                 101
#define IDS_TM_VIEW6_PPG_CAPTION        200
#define IDD_PROPPAGE_TM_VIEW6           200
#define IDD_LEAD_DIALOG                 201
#define IDS_FILENOTFOUND                201
#define IDS_TMV_FILENOTFOUND            201
#define IDC_LEADCTRL                    202
#define IDS_TMV_UNKNOWNERROR            202
#define IDS_TMV_NOIMAGE                 203
#define IDS_TMV_PAGEBOUNDRYEXCEEDED     204
#define IDD_TESTCTRL                    205
#define IDS_TMV_LOWMEMORY               205
#define IDS_TMV_FILEREAD                206
#define IDS_TMV_INVALIDNAME             207
#define IDD_ANNOTATION                  208
#define IDC_BACKGROUND                  208
#define IDS_TMV_FILEFORMAT              208
#define IDC_SCALEIMAGE                  209
#define IDS_TMV_INVALIDSUBTYPE          209
#define IDC_FITTOIMAGE                  210
#define IDS_TMV_FILEOPEN                210
#define IDC_SPINROTATION                211
#define IDS_TMV_COMPRESSION             211
#define IDC_ROTATIONLABEL               212
#define IDS_TMV_NOTANIMATION            212
#define IDD_CALLOUT                     212
#define IDC_LEADCTRL1                   213
#define IDS_TMV_STARTJOBFAILED          213
#define IDC_SPINFRAMETHICK              213
#define IDD_ABOUTBOX_TMVIEW             213
#define IDC_LEAD                        213
#define IDS_TMV_NODEFAULTPRINTER        214
#define IDC_NWCURSOR                    214
#define IDC_SPINSPLITTHICK              214
#define IDD_IMAGE_PROPERTIES            214
#define IDC_HIDESCROLLBARS              215
#define IDS_TMV_ZAPNOTFOUND             215
#define IDC_SWCURSOR                    215
#define IDD_CLEANUP                     215
#define IDC_PANPERCENTAGELABEL          216
#define IDS_TMV_INVALIDZAP              216
#define IDC_LEFTCURSOR                  216
#define IDD_PRINTPAGE                   216
#define IDC_INITIALNONE                 217
#define IDC_RIGHTCURSOR                 217
#define IDS_TMV_NOCALLOUTWND            217
#define IDD_PRINTER_CAPS                217
#define IDC_INITIALWIDTH                218
#define IDC_NECURSOR                    218
#define IDS_TMV_NOCONTAINER             218
#define IDC_INITIALHEIGHT               219
#define IDC_DOWNCURSOR                  219
#define IDS_TMV_CREATEANNFAILED         219
#define IDC_UPCUR                       220
#define IDS_TMV_ANNCOPYFAILED           220
#define IDC_SPINSELECT                  220
#define IDC_SECURSOR                    221
#define IDC_MOUSEPAN                    221
#define IDC_RIGHTCLICKPAN               221
#define IDS_TMV_INSERTCOPYFAILED        221
#define IDC_DOWN                        222
#define IDC_CALLOUT                     222
#define IDS_TMV_INVALIDZAPVIEW          222
#define IDC_DOWNRIGHT                   223
#define IDC_FRAMECOLOR                  223
#define IDS_TMV_LZWLOCKED               223
#define IDC_RIGHT                       224
#define IDC_SPLITFRAME                  224
#define IDS_TMV_PASTEFAILED             224
#define IDC_LEFT                        225
#define IDC_SPLITSCREEN                 225
#define IDS_TMV_COPYFAILED              225
#define IDC_UP                          226
#define IDC_SYNCPANES                   226
#define IDS_TMV_INVALIDCLIPBOARD        226
#define IDC_UPLEFT                      227
#define IDC_SYNCCALLOUTANN              227
#define IDS_TMV_NOBACKUP                227
#define IDC_DOWNLEFT                    228
#define IDC_SELECTVISIBLE               228
#define IDS_TMV_ANNNOTFOUND             228
#define IDC_UPRIGHT                     229
#define IDC_SELECTCOLOR                 229
#define IDS_TMV_ANNLOCKED               229
#define IDC_KEEPASPECT                  230
#define IDS_TMV_OPENINIFAILED           230
#define IDC_BITONAL                     231
#define IDC_ZOOMCURSOR                  231
#define IDC_SELECTCURSOR                232
#define IDC_ZOOMTORECT                  232
#define IDC_LINECURSOR                  233
#define IDC_ANNTOOL                     233
#define IDC_ANNTEXT                     233
#define IDC_RECTANGLECURSOR             234
#define IDC_FONTSIZE                    234
#define IDC_SIXTEEN_COLOR               234
#define IDC_CIRCLECURSOR                235
#define IDC_RESIZEABLE_CALLOUTS         235
#define IDC_CALLOUTCURSOR               236
#define IDC_FONTNAME                    236
#define IDC_HIGHLIGHTCURSOR             237
#define IDC_UNDERLINE                   237
#define IDC_HANDLECOLOR                 237
#define IDC_REDACTCURSOR                238
#define IDC_STRIKETHROUGH               238
#define IDC_FONT                        238
#define IDC_BOLD                        239
#define IDC_FILENAME                    239
#define IDC_CUTOUT_HIGHLIGHTS           239
#define IDC_SHADEONCALLOUT              239
#define IDC_CUTOUTBACKGROUNDCOLOR       240
#define IDC_PAN_CALLOUTS                240
#define IDC_DIM_PIXELS                  241
#define IDC_ZOOM_CALLOUTS               241
#define IDC_DIM_INCHES                  242
#define IDC_BITSPERPIXEL                243
#define IDC_SIZEDISK                    244
#define IDC_CLEAN                       244
#define IDC_SIZERAM                     245
#define IDUNDO                          245
#define IDC_PAGE                        246
#define IDC_DESKEW                      246
#define IDC_COMPRESSION                 247
#define IDC_DESPECKLE                   247
#define IDC_IMAGE_TYPE                  248
#define IDC_SMOOTH                      248
#define IDC_REMOVEHOLES                 249
#define IDC_REMOVEDOTS                  250
#define IDC_REMOVEBORDERS               251
#define IDC_SMOOTH_LENGTH_LABEL         252
#define IDC_SMOOTH_LENGTH               253
#define IDC_SMOOTH_LONG                 254
#define IDC_SMOOTH_GROUP                255
#define IDC_DOTS_MIN_WIDTH              256
#define IDC_DOTS_MIN_HEIGHT_LABEL       257
#define IDC_DOTS_MIN_HEIGHT             258
#define IDC_DOTS_MAX_WIDTH_LABEL        259
#define IDC_DOTS_MAX_WIDTH              260
#define IDC_DOTS_MAX_HEIGHT             261
#define IDC_DOTS_GROUP                  262
#define IDC_HOLES_MIN_WIDTH             263
#define IDC_HOLES_MIN_HEIGHT            264
#define IDC_HOLES_MAX_WIDTH             265
#define IDC_HOLES_MAX_HEIGHT            266
#define IDC_SAVE                        267
#define IDC_DESKEW_GROUP                268
#define IDC_DESKEW_COLOR                269
#define IDC_BORDERS_NOISE               272
#define IDC_BORDERS_PERCENT             273
#define IDC_BORDERS_VARIANCE            274
#define IDC_BORDERS_VARIANCE_LABEL      275
#define IDC_BORDERS_LEFT                276
#define IDC_BORDERS_RIGHT               277
#define IDC_BORDERS_TOP                 278
#define IDC_BORDERS_BOTTOM              279
#define IDC_HOLES_MAX_HEIGHT_LABEL      280
#define IDC_HOLES_MIN_WIDTH_LABEL       281
#define IDC_HOLES_LEFT                  282
#define IDC_HOLES_RIGHT                 283
#define IDC_DOTS_MIN_WIDTH_LABEL        284
#define IDC_DOTS_MAX_HEIGHT_LABEL       285
#define IDC_BORDERS_GROUP               286
#define IDC_HOLES_MAX_WIDTH_LABEL       287
#define IDC_HOLES_MIN_HEIGHT_LABEL      288
#define IDC_HOLES_GROUP                 289
#define IDC_HOLES_TOP                   290
#define IDC_HOLES_BOTTOM                291
#define IDC_BORDERS_NOISE_LABEL         292
#define IDC_BORDERS_PERCENT_LABEL       293
#define IDC_REMOVE_BORDERS_GROUP        294
#define IDC_DESKEW_COLOR_LABEL          295
#define IDC_LEFT_MARGIN                 298
#define IDC_RIGHT_MARGIN                299
#define IDC_TOP_MARGIN                  300
#define IDC_BOTTOM_MARGIN               301
#define IDC_BORDER_THICKNESS            302
#define IDC_BORDER_COLOR                303
#define IDC_ORIENTATION                 304
#define IDC_PRINT_CALLUTS               305
#define IDC_PRINT_CALLOUTS              305
#define IDC_PRINT_BORDER                306
#define IDC_DEVICE_CAPS                 306
#define IDC_PRINT_CALLOUT_BORDERS       307
#define IDC_PRINTERS                    307
#define IDC_DEVMODE                     308
#define IDC_BUTTON1                     308
#define IDC_LIST                        1000
#define IDC_RED                         1005
#define IDC_GREEN                       1006
#define IDC_BLUE                        1007
#define IDC_MAGENTA                     1008
#define IDC_YELLOW                      1009
#define IDC_CYAN                        1010
#define IDC_BLACK                       1011
#define IDC_GREY                        1012
#define IDC_WHITE                       1013
#define IDC_DRAWTOOL                    1014
#define IDC_HIGHLIGHT                   1015
#define IDC_REDACT                      1016
#define IDC_ELLIPSE                     1017
#define IDC_DARKRED                     1017
#define IDC_RECTANGLE                   1018
#define IDC_DARKBLUE                    1018
#define IDC_FELLIPSE                    1019
#define IDC_DARKGREEN                   1019
#define IDC_FRECTANGLE                  1020
#define IDC_LIGHTRED                    1020
#define IDC_LINE                        1021
#define IDC_LIGHTBLUE                   1021
#define IDC_LIGHTGREEN                  1022
#define IDC_THICKNESS                   1023
#define IDC_ZOOMFACTOR                  1024
#define IDC_DEFAULTS                    1025
#define IDC_SPINTHICK                   1026
#define IDC_SPINZOOM                    1027
#define IDC_ROTATION                    1028
#define IDC_PANPERCENTAGE               1029
#define IDC_SPINPAN                     1030
#define IDC_FREEHAND                    1031
#define IDC_POINTER                     1032
#define IDC_FRAMETHICK                  1033
#define IDC_SPLITTHICK                  1034
#define IDC_SELECTSIZE                  1035
#define IDC_SHADE_GRAYSCALE             1036
#define IDC_PANCURSOR                   10002
#define IDC_PLUS                        11001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        243
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         309
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
