#if !defined(AFX_TMGRAB_H__D1434E93_AD62_4957_8B14_1F94A2EF6D95__INCLUDED_)
#define AFX_TMGRAB_H__D1434E93_AD62_4957_8B14_1F94A2EF6D95__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTMGrab wrapper class

class CTMGrab : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTMGrab)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x4ba3488c, 0x31ec, 0x4619, { 0x9d, 0x96, 0x1e, 0xfe, 0x59, 0x2d, 0xd8, 0x61 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetVerBuild();
	void SetVerBuild(short);
	BOOL GetEnableErrors();
	void SetEnableErrors(BOOL);
	short GetVerMajor();
	void SetVerMajor(short);
	short GetVerMinor();
	void SetVerMinor(short);
	CString GetVerTextLong();
	void SetVerTextLong(LPCTSTR);
	CString GetIniFile();
	void SetIniFile(LPCTSTR);
	short GetArea();
	void SetArea(short);
	BOOL GetSilent();
	void SetSilent(BOOL);
	short GetHotkey();
	void SetHotkey(short);
	short GetCancelKey();
	void SetCancelKey(short);
	short GetVerQEF();
	void SetVerQEF(short);
	CString GetVerTextShort();
	void SetVerTextShort(LPCTSTR);
	CString GetVerBuildDate();
	void SetVerBuildDate(LPCTSTR);

// Operations
public:
	CString GetRegisteredPath();
	CString GetClassIdString();
	short Initialize();
	short Capture();
	short Stop();
	short Save(LPCTSTR pszName, short iFormat, short iBitsPerPixel, short iQuality, short iModify);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TMGRAB_H__D1434E93_AD62_4957_8B14_1F94A2EF6D95__INCLUDED_)
