// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "tmsetup.h"

/////////////////////////////////////////////////////////////////////////////
// CTMSetup

IMPLEMENT_DYNCREATE(CTMSetup, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTMSetup properties

BOOL CTMSetup::GetAutoInit()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetAutoInit(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

CString CTMSetup::GetIniFile()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CTMSetup::SetIniFile(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

BOOL CTMSetup::GetEnableErrors()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetEnableErrors(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

short CTMSetup::GetVerMajor()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CTMSetup::SetVerMajor(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

short CTMSetup::GetVerMinor()
{
	short result;
	GetProperty(0x5, VT_I2, (void*)&result);
	return result;
}

void CTMSetup::SetVerMinor(short propVal)
{
	SetProperty(0x5, VT_I2, propVal);
}

CString CTMSetup::GetVerTextLong()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CTMSetup::SetVerTextLong(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

short CTMSetup::GetVerBuild()
{
	short result;
	GetProperty(0x7, VT_I2, (void*)&result);
	return result;
}

void CTMSetup::SetVerBuild(short propVal)
{
	SetProperty(0x7, VT_I2, propVal);
}

OLE_COLOR CTMSetup::GetBackColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_BACKCOLOR, VT_I4, (void*)&result);
	return result;
}

void CTMSetup::SetBackColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_BACKCOLOR, VT_I4, propVal);
}

BOOL CTMSetup::GetAboutPage()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetAboutPage(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CTMSetup::GetDatabasePage()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetDatabasePage(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

BOOL CTMSetup::GetDirectXPage()
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetDirectXPage(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

BOOL CTMSetup::GetDiagnosticPage()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetDiagnosticPage(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

BOOL CTMSetup::GetGraphicsPage()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetGraphicsPage(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

BOOL CTMSetup::GetSystemPage()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetSystemPage(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

BOOL CTMSetup::GetTextPage()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetTextPage(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

BOOL CTMSetup::GetVideoPage()
{
	BOOL result;
	GetProperty(0xf, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetVideoPage(BOOL propVal)
{
	SetProperty(0xf, VT_BOOL, propVal);
}

CString CTMSetup::GetAboutName()
{
	CString result;
	GetProperty(0x10, VT_BSTR, (void*)&result);
	return result;
}

void CTMSetup::SetAboutName(LPCTSTR propVal)
{
	SetProperty(0x10, VT_BSTR, propVal);
}

CString CTMSetup::GetAboutVersion()
{
	CString result;
	GetProperty(0x11, VT_BSTR, (void*)&result);
	return result;
}

void CTMSetup::SetAboutVersion(LPCTSTR propVal)
{
	SetProperty(0x11, VT_BSTR, propVal);
}

CString CTMSetup::GetAboutCopyright()
{
	CString result;
	GetProperty(0x12, VT_BSTR, (void*)&result);
	return result;
}

void CTMSetup::SetAboutCopyright(LPCTSTR propVal)
{
	SetProperty(0x12, VT_BSTR, propVal);
}

CString CTMSetup::GetAboutPhone()
{
	CString result;
	GetProperty(0x13, VT_BSTR, (void*)&result);
	return result;
}

void CTMSetup::SetAboutPhone(LPCTSTR propVal)
{
	SetProperty(0x13, VT_BSTR, propVal);
}

CString CTMSetup::GetAboutEmail()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}

void CTMSetup::SetAboutEmail(LPCTSTR propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}

BOOL CTMSetup::GetCapturePage()
{
	BOOL result;
	GetProperty(0x100, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetCapturePage(BOOL propVal)
{
	SetProperty(0x100, VT_BOOL, propVal);
}

BOOL CTMSetup::GetRingtailPage()
{
	BOOL result;
	GetProperty(0x101, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetRingtailPage(BOOL propVal)
{
	SetProperty(0x101, VT_BOOL, propVal);
}

BOOL CTMSetup::GetEnableAxErrors()
{
	BOOL result;
	GetProperty(0x102, VT_BOOL, (void*)&result);
	return result;
}

void CTMSetup::SetEnableAxErrors(BOOL propVal)
{
	SetProperty(0x102, VT_BOOL, propVal);
}

short CTMSetup::GetVerQEF()
{
	short result;
	GetProperty(0x103, VT_I2, (void*)&result);
	return result;
}

void CTMSetup::SetVerQEF(short propVal)
{
	SetProperty(0x103, VT_I2, propVal);
}

CString CTMSetup::GetVerTextShort()
{
	CString result;
	GetProperty(0x104, VT_BSTR, (void*)&result);
	return result;
}

void CTMSetup::SetVerTextShort(LPCTSTR propVal)
{
	SetProperty(0x104, VT_BSTR, propVal);
}

CString CTMSetup::GetVerBuildDate()
{
	CString result;
	GetProperty(0x105, VT_BSTR, (void*)&result);
	return result;
}

void CTMSetup::SetVerBuildDate(LPCTSTR propVal)
{
	SetProperty(0x105, VT_BSTR, propVal);
}

CString CTMSetup::GetPresentationFileSpec()
{
	CString result;
	GetProperty(0x106, VT_BSTR, (void*)&result);
	return result;
}

void CTMSetup::SetPresentationFileSpec(LPCTSTR propVal)
{
	SetProperty(0x106, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CTMSetup operations

short CTMSetup::Initialize()
{
	short result;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CTMSetup::Save()
{
	short result;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CTMSetup::SetActiveFilters(LPCTSTR lpFilters, LPUNKNOWN lpMediaControl)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR VTS_UNKNOWN;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		lpFilters, lpMediaControl);
	return result;
}

CString CTMSetup::GetClassIdString()
{
	CString result;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CTMSetup::GetRegisteredPath()
{
	CString result;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CTMSetup::EnumAxVersions()
{
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CTMSetup::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
