#define TMax_Overview	2
#define TMax_Features	3
#define TMax_System_Requirements	10
#define TMax_Starting_the_program	27
#define TMax_Selecting_a_case	28
#define TMax_Setting_defaults	29
#define TMax_Retrieving_media	30
#define TMax_Annotation_Functions	31
#define TMax_Video_Functions	32
#define TMax_Exiting_the_program	33
//#define TMax_Hot-Key_list	34
#define TMax_Toolbar_button_list	35
#define TMax_Toolbar_configuration	36
#define TMax_DirectX_Options	8
#define TMax_Modifying_Hotkey_Assignments	9
#define TMax_Database_options	4
#define TMax_Text_Options	5
#define TMax_System_Options	7
