// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "tmgrab.h"

/////////////////////////////////////////////////////////////////////////////
// CTMGrab

IMPLEMENT_DYNCREATE(CTMGrab, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTMGrab properties

short CTMGrab::GetVerBuild()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CTMGrab::SetVerBuild(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

BOOL CTMGrab::GetEnableErrors()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CTMGrab::SetEnableErrors(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

short CTMGrab::GetVerMajor()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CTMGrab::SetVerMajor(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

short CTMGrab::GetVerMinor()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CTMGrab::SetVerMinor(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

CString CTMGrab::GetVerTextLong()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CTMGrab::SetVerTextLong(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

CString CTMGrab::GetIniFile()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CTMGrab::SetIniFile(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

short CTMGrab::GetArea()
{
	short result;
	GetProperty(0x7, VT_I2, (void*)&result);
	return result;
}

void CTMGrab::SetArea(short propVal)
{
	SetProperty(0x7, VT_I2, propVal);
}

BOOL CTMGrab::GetSilent()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CTMGrab::SetSilent(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

short CTMGrab::GetHotkey()
{
	short result;
	GetProperty(0x9, VT_I2, (void*)&result);
	return result;
}

void CTMGrab::SetHotkey(short propVal)
{
	SetProperty(0x9, VT_I2, propVal);
}

short CTMGrab::GetCancelKey()
{
	short result;
	GetProperty(0xa, VT_I2, (void*)&result);
	return result;
}

void CTMGrab::SetCancelKey(short propVal)
{
	SetProperty(0xa, VT_I2, propVal);
}

short CTMGrab::GetVerQEF()
{
	short result;
	GetProperty(0x100, VT_I2, (void*)&result);
	return result;
}

void CTMGrab::SetVerQEF(short propVal)
{
	SetProperty(0x100, VT_I2, propVal);
}

CString CTMGrab::GetVerTextShort()
{
	CString result;
	GetProperty(0x101, VT_BSTR, (void*)&result);
	return result;
}

void CTMGrab::SetVerTextShort(LPCTSTR propVal)
{
	SetProperty(0x101, VT_BSTR, propVal);
}

CString CTMGrab::GetVerBuildDate()
{
	CString result;
	GetProperty(0x102, VT_BSTR, (void*)&result);
	return result;
}

void CTMGrab::SetVerBuildDate(LPCTSTR propVal)
{
	SetProperty(0x102, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CTMGrab operations

CString CTMGrab::GetRegisteredPath()
{
	CString result;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CTMGrab::GetClassIdString()
{
	CString result;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

short CTMGrab::Initialize()
{
	short result;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CTMGrab::Capture()
{
	short result;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CTMGrab::Stop()
{
	short result;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CTMGrab::Save(LPCTSTR pszName, short iFormat, short iBitsPerPixel, short iQuality, short iModify)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		pszName, iFormat, iBitsPerPixel, iQuality, iModify);
	return result;
}

void CTMGrab::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
