//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tmgrabvc.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TMGRABVC_FORM               101
#define IDR_MAINFRAME                   128
#define IDR_TMGRABTYPE                  129
#define IDC_TMGRABCTRL1                 1000
#define ID_HOTKEY                       32771
#define ID_SILENT                       32772
#define ID_CAPTURE_FULLSCREEN           32773
#define ID_CAPTURE_ACTIVE               32774
#define ID_CAPTURE_SELECTION            32775
#define ID_CAPTURE                      32776
#define ID_STOP                         32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
