#if !defined(AFX_TMBARS_H__60FBB95A_B0F6_4C43_AAA5_5CB2349F2AB8__INCLUDED_)
#define AFX_TMBARS_H__60FBB95A_B0F6_4C43_AAA5_5CB2349F2AB8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTMBars wrapper class

class CTMBars : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTMBars)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5284e5b7, 0x9e77, 0x4200, { 0x9e, 0x9f, 0xd5, 0xf2, 0x2c, 0xb4, 0xf, 0x2c } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetAutoInit();
	void SetAutoInit(BOOL);
	short GetVerBuild();
	void SetVerBuild(short);
	BOOL GetEnableErrors();
	void SetEnableErrors(BOOL);
	CString GetIniFile();
	void SetIniFile(LPCTSTR);
	short GetVerMajor();
	void SetVerMajor(short);
	short GetVerMinor();
	void SetVerMinor(short);
	CString GetVerTextLong();
	void SetVerTextLong(LPCTSTR);
	short GetVerQEF();
	void SetVerQEF(short);
	CString GetVerTextShort();
	void SetVerTextShort(LPCTSTR);
	CString GetVerBuildDate();
	void SetVerBuildDate(LPCTSTR);

// Operations
public:
	short Initialize();
	short Save();
	CString GetClassIdString();
	CString GetRegisteredPath();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TMBARS_H__60FBB95A_B0F6_4C43_AAA5_5CB2349F2AB8__INCLUDED_)
