//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by F:\Tmaxnet\Presentation\Tmshare\Tm_share6.rc
//
#define IDS_TM_SHARE6                   1
#define IDD_ABOUTBOX_TM_SHARE6          1
#define IDB_TM_SHARE6                   1
#define IDI_ABOUTDLL                    1
#define IDD_ABOUTBOX_TMSHARE            1
#define IDB_TMSHARE                     1
#define IDS_TMSHARE                     1
#define IDS_TM_SHARE6_PPG               2
#define IDS_TMSHARE_PPG                 2
#define IDS_TM_SHARE6_PPG_CAPTION       200
#define IDD_PROPPAGE_TM_SHARE6          200
#define IDD_PROPPAGE_TMSHARE            200
#define IDS_TMSHARE_PPG_CAPTION         200
#define IDS_OPENSHAREDFAILED            201
#define IDS_OPEN_PRESENTATION_REQUEST_FAILED 201
#define IDS_OPEN_PRESENTATION_RESPONSE_FAILED 202
#define IDS_OPEN_MANAGER_RESPONSE_FAILED 203
#define IDS_OPEN_MANAGER_REQUEST_FAILED 204
#define IDS_COMMAND_REQUEST_TIMER_FAILED 205
#define IDS_NOT_INITIALIZED             206
#define IDS_WRITE_PRESENTATION_REQUEST_FAILED 207
#define IDS_WRITE_PRESENTATION_RESPONSE_FAILED 208
#define IDS_WRITE_MANAGER_RESPONSE_FAILED 209
#define IDS_WRITE_MANAGER_REQUEST_FAILED 210
#define IDS_READ_PRESENTATION_REQUEST_FAILED 211
#define IDS_READ_PRESENTATION_RESPONSE_FAILED 212
#define IDS_READ_MANAGER_RESPONSE_FAILED 213
#define IDS_READ_MANAGER_REQUEST_FAILED 214
#define IDS_REQUEST_TIMED_OUT           215
#define IDS_OPEN_PRESENTATION_STATUS_FAILED 216
#define IDS_OPEN_MANAGER_STATUS_FAILED  217
#define IDS_WRITE_PRESENTATION_STATUS_FAILED 218
#define IDS_WRITE_MANAGER_STATUS_FAILED 219
#define IDS_READ_PRESENTATION_STATUS_FAILED 220
#define IDS_READ_MANAGER_STATUS_FAILED  221
#define IDS_TMSHARE_ERROR_SINGLE_INSTANCE 222

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
