// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "tmbars.h"

/////////////////////////////////////////////////////////////////////////////
// CTMBars

IMPLEMENT_DYNCREATE(CTMBars, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTMBars properties

BOOL CTMBars::GetAutoInit()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CTMBars::SetAutoInit(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

short CTMBars::GetVerBuild()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CTMBars::SetVerBuild(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

BOOL CTMBars::GetEnableErrors()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CTMBars::SetEnableErrors(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

CString CTMBars::GetIniFile()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CTMBars::SetIniFile(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

short CTMBars::GetVerMajor()
{
	short result;
	GetProperty(0x5, VT_I2, (void*)&result);
	return result;
}

void CTMBars::SetVerMajor(short propVal)
{
	SetProperty(0x5, VT_I2, propVal);
}

short CTMBars::GetVerMinor()
{
	short result;
	GetProperty(0x6, VT_I2, (void*)&result);
	return result;
}

void CTMBars::SetVerMinor(short propVal)
{
	SetProperty(0x6, VT_I2, propVal);
}

CString CTMBars::GetVerTextLong()
{
	CString result;
	GetProperty(0x7, VT_BSTR, (void*)&result);
	return result;
}

void CTMBars::SetVerTextLong(LPCTSTR propVal)
{
	SetProperty(0x7, VT_BSTR, propVal);
}

short CTMBars::GetVerQEF()
{
	short result;
	GetProperty(0x100, VT_I2, (void*)&result);
	return result;
}

void CTMBars::SetVerQEF(short propVal)
{
	SetProperty(0x100, VT_I2, propVal);
}

CString CTMBars::GetVerTextShort()
{
	CString result;
	GetProperty(0x101, VT_BSTR, (void*)&result);
	return result;
}

void CTMBars::SetVerTextShort(LPCTSTR propVal)
{
	SetProperty(0x101, VT_BSTR, propVal);
}

CString CTMBars::GetVerBuildDate()
{
	CString result;
	GetProperty(0x102, VT_BSTR, (void*)&result);
	return result;
}

void CTMBars::SetVerBuildDate(LPCTSTR propVal)
{
	SetProperty(0x102, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CTMBars operations

short CTMBars::Initialize()
{
	short result;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CTMBars::Save()
{
	short result;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

CString CTMBars::GetClassIdString()
{
	CString result;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CTMBars::GetRegisteredPath()
{
	CString result;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}
