#ifndef __SAVETYPE_H__
#define __SAVETYPE_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLEADSaveType wrapper class

class CLEADSaveType : public COleDispatchDriver
{
public:
	CLEADSaveType() {}		// Calls COleDispatchDriver default constructor
	CLEADSaveType(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLEADSaveType(const CLEADSaveType& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	// method 'QueryInterface' not emitted because of invalid return type or parameter type
	unsigned long AddRef();
	unsigned long Release();
	// method 'GetTypeInfoCount' not emitted because of invalid return type or parameter type
	// method 'GetTypeInfo' not emitted because of invalid return type or parameter type
	// method 'GetIDsOfNames' not emitted because of invalid return type or parameter type
	// method 'Invoke' not emitted because of invalid return type or parameter type
	long GetFormat();
	void SetFormat(long nNewValue);
	long GetSubFormatFlags();
	void SetSubFormatFlags(long nNewValue);
};

#endif // __SAVETYPE_H__
