//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D:\TrialMax\sourcecode\Trialmax\TmaxPresentation\Tmsetup\Tm_setup6.rc
//
#define IDS_TMSETUP                     1
#define IDD_ABOUTBOX_TMSETUP            1
#define IDB_TMSETUP                     1
#define IDI_ABOUTDLL                    1
#define IDS_TMSETUP_PPG                 2
#define IDR_MAINFRAME                   128
#define IDS_TMSETUP_PPG_CAPTION         200
#define IDD_PROPPAGE_TMSETUP            200
#define IDS_TMSETUP_NOTINITIALIZED      201
#define IDC_TMPRINT                     202
#define IDS_TMSETUP_INVALIDTHICKNESS    202
#define IDS_TMSETUP_INVALIDZOOMFACTOR   203
#define IDC_TMVIEW                      204
#define IDS_TMSETUP_INVALIDCHARSPERLINE 204
#define IDC_TMTOOL                      205
#define IDS_TMSETUP_INVALIDHIGHLIGHTLINES 205
#define IDC_TMTEXT                      206
#define IDS_TMSETUP_INVALIDDISPLAYLINES 206
#define IDC_TMSTAT                      207
#define IDS_TMSETUP_INVALIDFRAMERATE    207
#define IDC_TMPOWER                     208
#define IDC_TMMOVIE                     209
#define IDC_TMLPEN                      210
#define IDC_TMBARS                      211
#define IDC_TMSETUP                     212
#define IDC_NAME                        212
#define IDC_COPYRIGHT                   213
#define IDC_PHONE                       214
#define IDC_EMAIL                       215
#define IDC_IMAGE_ID                    226
#define IDC_IMAGE_ORDER                 227
#define IDC_CASES                       227
#define IDC_ANIMATION_ID                228
#define IDC_LIST                        228
#define IDC_ANIMATION_ORDER             229
#define IDC_SILENT                      229
#define IDC_PLAYLIST_ID                 230
#define IDC_AREA                        230
#define IDC_PLAYLIST_ORDER              231
#define IDC_HOTKEY                      231
#define IDC_POWERPOINT_ID               232
#define IDC_POWERPOINT_ORDER            233
#define IDC_POWERPOINT_INDEX            234
#define IDC_TREATMENT_ID                235
#define IDC_TREATMENT_ORDER             236
#define IDC_SHOW_ID                     237
#define IDC_SHOW_ORDER                  238
#define IDC_OPTIMIZE_VIDEO              239
#define IDC_RINGTAIL_REDACTCOLOR        240
#define IDC_DUAL_MONITORS               240
#define IDC_RINGTAIL_REDACTLABELCOLOR   241
#define IDC_OPTIMIZE_VIDEO2             241
#define IDC_OPTIMIZE_TABLET             241
#define IDC_REDACTLABEL_FONTS           242
#define IDC_RINGTAIL_REDACTLABELSIZE    243
#define IDC_RINGTAIL_SHOWREDACTIONS     244
#define IDC_RINGTAIL_REDACTTRANSPARENCY 245
#define IDC_BACKCOLOR_LABEL             246
#define IDC_FORECOLOR_LABEL             247
#define IDC_HIGHCOLOR_LABEL             248
#define IDC_HIGHTEXTCOLOR_LABEL         249
#define IDC_TMSHARECTRL1                250
#define IDC_TMSHARE                     250
#define IDC_BULLETS_LABEL               250
#define IDC_TMGRAB                      251
#define IDC_ENABLE_BARCODE_KEYSTROKES   254
#define IDD_GRAPHICS_PAGE               301
#define IDD_SIZE_DIALOG                 510
#define IDD_VIDEO_PAGE                  511
#define IDD_TEXT_PAGE                   512
#define IDD_ABOUT_PAGE                  513
#define IDD_DATABASE_PAGE               514
#define IDD_DIAGNOSTIC_PAGE             515
#define IDD_DIRECTX_PAGE                516
#define IDD_SYSTEM_PAGE                 517
#define IDD_CONTROLS                    518
#define IDD_CAPTURE_PAGE                519
#define IDD_RINGTAIL_PAGE               520
#define IDC_CASESFOLDER                 1001
#define IDC_CURRENT                     1001
#define IDC_FILENAME                    1002
#define IDC_TEXT_DISPLAYLINES           1003
#define IDC_DEFAULTDRIVE                1003
#define IDC_TEXT_SCROLLSTEPS            1004
#define IDC_BROWSEFOLDER                1005
#define IDC_RED                         1005
#define IDC_GREEN                       1006
#define IDC_BLUE                        1007
#define IDC_MAGENTA                     1008
#define IDC_YELLOW                      1009
#define IDC_CYAN                        1010
#define IDC_BLACK                       1011
#define IDC_USEDEFAULT                  1011
#define IDC_GREY                        1012
#define IDC_SCALEAVICLIPS               1012
#define IDC_ENABLEERRORS                1013
#define IDC_WHITE                       1013
#define IDC_ENABLEPOWERPOINT            1014
#define IDC_DRAWTOOL                    1014
#define IDC_PLAYLISTSTEP                1014
#define IDC_HIGHLIGHT                   1015
#define IDC_CLEARPLAYLIST               1015
#define IDC_REDACT                      1016
#define IDC_RESUMEPLAYLIST              1016
#define IDC_TMCASEVERSION               1017
#define IDC_DARKRED                     1017
#define IDC_CLIPSTEP                    1017
#define IDC_TMMOVIEVERSION              1018
#define IDC_DARKBLUE                    1018
#define IDC_CLEARCLIP                   1018
#define IDC_TMVIEWVERSION               1019
#define IDC_DARKGREEN                   1019
#define IDC_RESUMECLIP                  1019
#define IDC_TMAXVERSION                 1020
#define IDC_LIGHTRED                    1020
#define IDC_CLIPSASPLAYLISTS            1020
#define IDC_TMSTATVERSION               1021
#define IDC_LIGHTBLUE                   1021
#define IDC_RUNTOEND                    1021
#define IDC_BROWSE                      1022
#define IDC_FRAMERATE                   1022
#define IDC_ABOUT_VERSION               1023
#define IDC_TMTOOLVERSION               1023
#define IDC_THICKNESS                   1023
#define IDC_VERSION                     1023
#define IDC_SPLITDOCUMENTS              1023
#define IDC_TMTEXTVERSION               1024
#define IDC_ZOOMFACTOR                  1024
#define IDC_SPLITGRAPHICS               1024
#define IDC_TMLPENVERSION               1025
#define IDC_SCALEGRAPHICS               1025
#define IDC_SPLITPOWERPOINTS            1025
#define IDC_CASELIST                    1026
#define IDC_TMPOWERVERSION              1026
#define IDC_SPINTHICK                   1026
#define IDC_CLASSIC_LINKS               1026
#define IDC_MSPOWERVERSION              1027
#define IDC_SPINZOOM                    1027
#define IDC_SCALEDOCS                   1028
#define IDC_PROPERTIES                  1029
#define IDC_RESTRICTZOOM                1029
#define IDC_TEXT_BACKCOLOR              1029
#define IDC_SHADE_GRAYSCALE             1029
#define IDC_CALLFRAMETHICK              1030
#define IDC_LIGHTGREEN                  1031
#define IDC_CALLFRAMETHICKSPIN          1033
#define IDC_LIGHTPENSIZE                1034
#define IDC_LIGHTPENSIZESPIN            1035
#define IDC_LIGHTPENCONTROLS            1036
#define IDC_RESIZABLE_CALLOUTS          1037
#define IDC_SHADE_CALLOUTS              1038
#define IDC_PAN_CALLOUTS                1039
#define IDC_ACTIVE                      1056
#define IDC_REGISTERED                  1057
#define IDC_CALLOUT                     1065
#define IDC_CALLOUTFRAME                1066
#define IDC_LIGHTPENRECT                1067
#define IDC_BITONAL                     1068
#define IDC_CALLOUTHANDLES              1069
#define IDC_USERSPLITFRAMECOLOR         1070
#define IDC_SYSTEM_MEDIABARCODES        1071
#define IDC_ZAPSPLITFRAMECOLOR          1071
#define IDC_SYSTEM_PLAYLISTBARCODES     1072
#define IDC_SYSTEM_USECASEDRIVE         1073
#define IDC_TEXT_FONTS                  1075
#define IDC_TEXT_AVGCHARWIDTH           1076
#define IDC_TEXT_SHOWPAGELINE           1077
#define IDC_TEXT_HIGHLIGHTLINES         1078
#define IDC_TEXT_MAXCHARSPERLINE        1079
#define IDC_TEXT_FORECOLOR              1080
#define IDC_TEXT_HIGHLIGHTCOLOR         1081
#define IDC_TEXT_HIGHTEXTCOLOR          1082
#define IDC_TEXT_CENTERVIDEO            1083
#define IDC_TEXT_SCROLLTIME             1084
#define IDC_VIDEO4                      1084
#define IDC_VIDEO6                      1085
#define IDC_TEXT_LEFT_MARGIN            1085
#define IDC_VIDEO8                      1086
#define IDC_TEXT_TOP_MARGIN             1086
#define IDC_UPPERLEFT                   1087
#define IDC_TEXT_RIGHT_MARGIN           1087
#define IDC_COMBINETEXT                 1088
#define IDC_UPPERRIGHT                  1088
#define IDC_LOWERLEFT                   1089
#define IDC_USEMANAGERHIGHLIGHTERS      1089
#define IDC_VIDEO0                      1090
#define IDC_TEXT_BOTTOM_MARGIN          1090
#define IDC_LOWERRIGHT                  1091
#define IDC_TEXT_SHOWTEXT               1091
#define IDC_TEXT_SMOOTHSCROLL           1092
#define IDC_TEXT_DISABLESCROLLTEXT      1093
#define IDC_BULLET_STYLE                1094
#define IDC_ANNTOOL                     1095
#define IDC_CHANGEFONT                  1096
#define IDC_FONTNAME                    1097
#define IDC_FILEPATH					1125
#define IDC_BROWSEFILEPATH				1126

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         255
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
