//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D:\TrialMax-Hussain\TrialMax\sourcecode\Trialmax\TmaxPresentation\App\TmaxPresentation.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUT_PAGE                  100
#define IDD_TMAXPRESENTATION_FORM       101
#define IDB_VKB                         104
#define IDR_MAINFRAME                   128
#define IDR_TMVIEWTYPE                  129
#define IDB_HRPREVIOUS                  140
#define IDB_HRNEXT                      141
#define IDB_HRCW                        142
#define IDB_HRCCW                       143
#define IDB_HRNORMAL                    144
#define IDB_HRZOOM                      145
#define IDB_HRHIGHLIGHT                 146
#define IDB_HRREDACT                    147
#define IDB_HRDRAW                      148
#define IDB_HRERASE                     149
#define IDB_HRCLEAR                     150
#define IDB_HREXIT                      151
#define IDB_HRPLAY                      152
#define IDB_HRPREVIOUSD                 170
#define IDB_HRNEXTD                     171
#define IDB_HRCWD                       172
#define IDB_HRCCWD                      173
#define IDB_HRNORMALD                   174
#define IDB_HRZOOMD                     175
#define IDB_HRHIGHLIGHTD                176
#define IDB_HRREDACTD                   177
#define IDB_HRDRAWD                     178
#define IDB_HRERASED                    179
#define IDB_HRCLEARD                    180
#define IDB_HREXITD                     181
#define IDB_HRPLAYD                     182
#define IDB_MRPREVIOUS                  200
#define IDB_MRNEXT                      201
#define IDB_MRCW                        202
#define IDB_MRCCW                       203
#define IDB_MRNORMAL                    204
#define IDB_MRZOOM                      205
#define IDB_MRHIGHLIGHT                 206
#define IDB_MRREDACT                    207
#define IDB_MRDRAW                      208
#define IDB_MRERASE                     209
#define IDB_MRCLEAR                     210
#define IDB_MREXIT                      211
#define IDB_MRPLAY                      212
#define IDB_MRPREVIOUSD                 230
#define IDB_MRNEXTD                     231
#define IDB_MRCWD                       232
#define IDB_MRCCWD                      233
#define IDB_MRNORMALD                   234
#define IDB_MRZOOMD                     235
#define IDB_MRHIGHLIGHTD                236
#define IDB_MRREDACTD                   237
#define IDB_MRDRAWD                     238
#define IDB_MRERASED                    239
#define IDB_MRCLEARD                    240
#define IDB_MREXITD                     241
#define IDB_MRPLAYD                     242
#define IDB_LRPREVIOUS                  260
#define IDB_LRNEXT                      261
#define IDB_LRCW                        262
#define IDB_LRCCW                       263
#define IDB_LRNORMAL                    264
#define IDB_LRZOOM                      265
#define IDB_LRHIGHLIGHT                 266
#define IDB_LRREDACT                    267
#define IDB_LRDRAW                      268
#define IDB_LRERASE                     269
#define IDB_LRCLEAR                     270
#define IDB_LREXIT                      271
#define IDB_LRPLAY                      272
#define IDB_LRPREVIOUSD                 290
#define IDB_LRNEXTD                     291
#define IDB_LRCWD                       292
#define IDB_LRCCWD                      293
#define IDB_LRNORMALD                   294
#define IDB_LRZOOMD                     295
#define IDB_LRHIGHLIGHTD                296
#define IDB_LRREDACTD                   297
#define IDB_LRDRAWD                     298
#define IDB_LRERASED                    299
#define IDB_LRCLEARD                    300
#define IDB_LREXITD                     301
#define IDB_LRPLAYD                     302
#define IDD_ANNOTATE_PAGE               320
#define IDD_GRAPHICS_PAGE               320
#define IDD_OPTIONS_PAGE                321
#define IDD_DATABASE_PAGE               321
#define IDB_PAUSED                      332
#define IDD_MANAGER                     333
#define IDD_DIAGNOSTIC_PAGE             334
#define IDD_PLAYLIST_PAGE               335
#define IDD_VIDEO_PAGE                  335
#define IDD_TMTOOL_PAGE                 336
#define IDB_TBBITMAPS                   337
#define IDD_SPLASHBOX                   340
#define IDB_SPLASHBOX                   341
#define IDD_DIRECTX_PAGE                341
#define IDD_PAGELINE                    343
#define IDD_SETLINE                     343
#define IDD_SYSTEM_PAGE                 344
#define IDD_TEXT_PAGE                   345
#define IDD_CONFIRM_EXIT                346
#define IDI_CONFIRM                     346
#define IDD_TOOLBARS                    347
#define IDD_SETUP                       348
#define IDD_CAPTURE                     353
#define IDC_CURSOR1                     356
#define IDD_KeyBoardDlg                 357
#define IDD_KeyBoardDlg1                358
#define IDB_PNG1                        366
#define IDB_BITMAP1                     367
#define IDD_BINDER_LIST                 368
#define IDB_BITMAP2                     370
#define IDB_FILEIMAGE                   371
#define IDB_FOLDERIMAGE                 372
#define IDB_FILEICON                    376
#define IDI_FOLDER                      381
#define IDI_FOLDER_BACK                 383
#define IDI_FILE                        384
#define IDI_ICON1                       386
#define IDI_ICON2                       387
#define IDI_CLOSE_FOLDER_BLACK          388
#define IDI_CLOSE_BLACK                 389
#define IDD_COLOR_PICKER_DLG            391
#define IDB_GEEN_COLOR                  397
#define IDC_CASEFOLDER                  1001
#define IDC_CASESFOLDER                 1001
#define IDC_FILENAME                    1002
#define IDC_EDIT1                       1003
#define IDC_DEFAULTDRIVE                1003
#define IDC_TEXT_DISPLAYLINES           1003
#define IDC_TEXT_SCROLLSTEPS            1004
#define IDC_RED                         1005
#define IDC_BROWSEFOLDER                1005
#define IDC_GREEN                       1006
#define IDC_BROWSEFILENAME              1006
#define IDC_BLUE                        1007
#define IDC_SCALEIMAGE                  1007
#define IDC_MAGENTA                     1008
#define IDC_ANIMATE1                    1008
#define IDC_ANIMATE                     1008
#define IDC_YELLOW                      1009
#define IDC_TMPLAYCTRL1                 1009
#define IDC_TMPLAYCTRL                  1009
#define IDC_CYAN                        1010
#define IDC_BLACK                       1011
#define IDC_USEDEFAULT                  1011
#define IDC_GREY                        1012
#define IDC_TMCASE                      1012
#define IDC_SCALEAVICLIPS               1012
#define IDC_WHITE                       1013
#define IDC_ENABLEERRORS                1013
#define IDC_DRAWTOOL                    1014
#define IDC_PLAYLISTSTEP                1014
#define IDC_ENABLEPOWERPOINT            1014
#define IDC_HIGHLIGHT                   1015
#define IDC_CLEARONFINISH               1015
#define IDC_CLEARPLAYLIST               1015
#define IDC_REDACT                      1016
#define IDC_AUTORESUME                  1016
#define IDC_RESUMEPLAYLIST              1016
#define IDC_ELLIPSE                     1017
#define IDC_TMCASEVERSION               1017
#define IDC_CLIPSTEP                    1017
#define IDC_DARKRED                     1017
#define IDC_RECTANGLE                   1018
#define IDC_TMPLAYVERSION               1018
#define IDC_CLEARCLIP                   1018
#define IDC_TMMOVIEVERSION              1018
#define IDC_DARKBLUE                    1018
#define IDC_FELLIPSE                    1019
#define IDC_TMVIEWVERSION               1019
#define IDC_RESUMECLIP                  1019
#define IDC_DARKGREEN                   1019
#define IDC_FRECTANGLE                  1020
#define IDC_TMAXVERSION                 1020
#define IDC_CLIPSASPLAYLISTS            1020
#define IDC_LIGHTRED                    1020
#define IDC_LINE                        1021
#define IDC_DEVICENAME                  1021
#define IDC_MPEGNAME                    1021
#define IDC_RUNTOEND                    1021
#define IDC_TMSTATVERSION               1021
#define IDC_LIGHTBLUE                   1021
#define IDC_DRIVERVERSION               1022
#define IDC_BROWSE                      1022
#define IDC_MPEGVERSION                 1022
#define IDC_FRAMERATE                   1022
#define IDC_THICKNESS                   1023
#define IDC_ABOUT_VERSION               1023
#define IDC_TMTOOLVERSION               1023
#define IDC_ZOOMFACTOR                  1024
#define IDC_CTRL1                       1024
#define IDC_AVINAME                     1024
#define IDC_TMTEXTVERSION               1024
#define IDC_SCALEGRAPHICS               1025
#define IDC_AVIVERSION                  1025
#define IDC_TMLPENVERSION               1025
#define IDC_SPINTHICK                   1026
#define IDC_CASELIST                    1026
#define IDC_TMPOWERVERSION              1026
#define IDC_SPINZOOM                    1027
#define IDC_MSPOWERVERSION              1027
#define IDC_SCALEDOCS                   1028
#define IDC_TMTB_REMOVE                 1029
#define IDC_PROPERTIES                  1029
#define IDC_LIGHTPEN                    1029
#define IDC_TEXT_BACKCOLOR              1029
#define IDC_RESTRICTZOOM                1029
#define IDC_CALLFRAMETHICK              1030
#define IDC_TBGRAPHICS                  1030
#define IDC_TOOLBAR                     1030
#define IDC_DOCUMENTS                   1030
#define IDC_THICKNESS2                  1030
#define IDC_FREEHAND                    1031
#define IDC_TBDOCUMENTS                 1031
#define IDC_LIGHTGREEN                  1031
#define IDC_DOCUMENTS2                  1031
#define IDC_GRAPHICS                    1031
#define IDC_POINTER                     1032
#define IDC_TBLINKS                     1032
#define IDC_DOCUMENTS3                  1032
#define IDC_DOCUMENTS_LARGE             1032
#define IDC_CALLFRAMETHICKSPIN          1033
#define IDC_TBPLAYLISTS                 1033
#define IDC_SPINTHICK2                  1033
#define IDC_LIGHTPENSIZE                1034
#define IDC_TBMOVIES                    1034
#define IDC_ZOOMFACTOR2                 1034
#define IDC_LIGHTPENSIZESPIN            1035
#define IDC_TMTOOL_VISIBLE              1035
#define IDC_SPINZOOM2                   1035
#define IDC_TMTOOL_FLOAT                1036
#define IDC_LIGHTPENCONTROLS            1036
#define IDC_TMTOOL_STRETCH              1037
#define IDC_TMTOOL_FLAT                 1038
#define IDC_TMTOOL_IMAGES               1039
#define IDC_TMTB_TOOLBAR                1040
#define IDC_TMTB_INSERT                 1041
#define IDC_TMTB_BEFORE                 1041
#define IDC_TMTB_AFTER                  1042
#define IDC_GRAPHICS2                   1044
#define IDC_PLAYLISTS                   1045
#define IDC_LINKS                       1046
#define IDC_MOVIES                      1047
#define IDC_TEXT                        1048
#define IDC_MPEGDESCRIPTION             1049
#define IDC_DRAWINGTOOLS                1049
#define IDC_AVIDESCRIPTION              1050
#define IDC_TMTOOL_SMALL                1050
#define IDC_POWERPOINT                  1050
#define IDC_TMTOOL_MEDIUM               1051
#define IDC_LINKPOWER                   1051
#define IDC_TMTOOL_LARGE                1052
#define IDC_BITMAP                      1053
#define IDC_TMMOVIECTRL                 1054
#define IDC_ACTIVE                      1056
#define IDC_REGISTERED                  1057
#define IDC_TMTOOL_TEMPLATES            1058
#define IDC_TMTOOL_LOAD                 1059
#define IDC_TMTOOL_SAVE                 1060
#define IDC_PL_PAGE                     1063
#define IDC_PAGE                        1063
#define IDC_PL_LINE                     1064
#define IDC_CALLOUT                     1065
#define IDC_CALLOUTFRAME                1066
#define IDC_LIGHTPENRECT                1067
#define IDC_BITONAL                     1068
#define IDC_PL_LABEL                    1069
#define IDC_LABEL                       1069
#define IDC_PL_ERROR                    1070
#define IDC_MESSAGE                     1070
#define IDC_SYSTEM_MEDIABARCODES        1071
#define IDC_SYSTEM_PLAYLISTBARCODES     1072
#define IDC_SYSTEM_USECASEDRIVE         1073
#define IDC_TMTEXTCTRL                  1074
#define IDC_TEXT_FONTS                  1075
#define IDC_TEXT_AVGCHARWIDTH           1076
#define IDC_TEXT_SHOWPAGELINE           1077
#define IDC_TEXT_HIGHLIGHTLINES         1078
#define IDC_TEXT_MAXCHARSPERLINE        1079
#define IDC_TEXT_FORECOLOR              1080
#define IDC_TEXT_HIGHLIGHTCOLOR         1081
#define IDC_TEXT_HIGHTEXTCOLOR          1082
#define IDC_TEXT_CENTERVIDEO            1083
#define IDC_VIDEO4                      1084
#define IDC_TEXT_SCROLLTIME             1084
#define IDC_VIDEO6                      1085
#define IDC_VIDEO8                      1086
#define IDC_COMBINETEXT                 1088
#define IDC_TMSTATCTRL                  1089
#define IDC_VIDEO0                      1090
#define IDC_TMLPENCTRL                  1091
#define IDC_TEXT_SMOOTHSCROLL           1092
#define IDC_TMPOWERCTRL                 1094
#define IDC_ANNTOOL                     1095
#define IDC_CHANGEFONT                  1096
#define IDC_FONTNAME                    1097
#define IDC_TMBARS                      1098
#define IDC_TMSETUP                     1099
#define IDC_TRANSCRIPTS                 1117
#define ID_SAVE_AS                      1119
#define ID_STOP                         1120
#define IDC_LEAD_CAPTURE                1121
#define IDC_LEAD                        1122
#define IDC_TMGRABCTRL                  1123
#define IDC_TMSHARECTRL1                1124
#define IDC_TMSHARE                     1124
#define IDC_FILEPATH                    1125
#define IDC_BROWSEFILEPATH              1126
#define IDC_TMVIEWCTRL                  5000
#define IDC_TMVIEWCTRL2                 5001
#define IDC_TMVIEWCTRL3                 5002
#define ID_NORMAL                       32701
#define ID_ZOOM                         32702
#define ID_NEXT                         32703
#define ID_PREVIOUS                     32704
#define ID_DRAW                         32705
#define ID_ERASE                        32706
#define ID_REDACT                       32707
#define ID_HIGHLIGHT                    32708
#define ID_ROTATE_CCW                   32709
#define ID_ROTATE_CW                    32710
#define ID_CONFIG                       32711
#define IDX_LOAD_AND_PLAY_PLAYLIST      32713
#define IDX_LOAD_DOCUMENT               32714
#define ID_PLAY                         32715
#define ID_PAUSE                        32716
#define ID_HOTKEY1                      32717
#define ID_CLEAR                        32718
#define ID_MANAGER                      32719
#define ID_ZAP_ADD                      32720
#define ID_ZAP_SAVE                     32721
#define ID_ZAP_FIRST                    32722
#define ID_ZAP_NEXT                     32723
#define ID_ZAP_LAST                     32724
#define ID_ZAP_PREVIOUS                 32725
#define ID_CALLOUT                      32726
#define ID_PAN                          32727
#define ID_ZOOMWIDTH                    32728
#define ID_FIRSTDESIGNATION             32729
#define ID_LASTDESIGNATION              32730
#define ID_NEXTDESIGNATION              32731
#define ID_PREVDESIGNATION              32732
#define ID_BACKDESIGNATION              32733
#define ID_FWDDESIGNATION               32734
#define ID_STARTMOVIE                   32735
#define ID_ENDMOVIE                     32736
#define ID_BACKMOVIE                    32737
#define ID_FWDMOVIE                     32738
#define ID_STARTDESIGNATION             32739
#define ID_TMTOOL                       32740
#define ID_ENABLELINKS                  32741
#define ID_DRAWRED                      32742
#define ID_DRAWGREEN                    32743
#define ID_DRAWBLUE                     32744
#define ID_DRAWYELLOW                   32745
#define ID_DRAWBLACK                    32746
#define ID_SPLITSCREEN                  32747
#define ID_DISABLELINKS                 32748
#define ID_DRAWWHITE                    32749
#define ID_FIRSTPAGE                    32750
#define ID_LASTPAGE                     32751
#define ID_FILTERPROPS                  32752
#define ID_SETPAGELINE                  32753
#define ID_SETPAGELINENEXT              32754
#define ID_DELETELASTANN                32755
#define ID_DELETEANN                    32755
#define ID_DELETESELECTIONS             32756
#define ID_SELECT                       32757
#define ID_PLAYTHROUGH                  32758
#define ID_VIDEOCAPTION                 32759
#define ID_TMAX_HELP                    32760
#define ID_TEXT                         32761
#define ID_SELECTTOOL                   32762
#define ID_FREEHAND                     32763
#define ID_LINE                         32764
#define ID_ARROW                        32765
#define ID_ELLPSE                       32766
#define ID_RECTANGLE                    32767
#define ID_FILLEDELLIPSE                32768
#define ID_FILLEDRECTANGLE              32769
#define ID_FULLSCREEN                   32770
#define ID_STATUSBAR                    32771
#define ID_DRAWDARKRED                  32772
#define ID_DRAWDARKGREEN                32773
#define ID_DRAWDARKBLUE                 32774
#define ID_DRAWLIGHTRED                 32775
#define ID_DRAWLIGHTGREEN               32776
#define ID_DRAWLIGHTBLUE                32777
#define ID_POLYLINE                     32778
#define ID_POLYGON                      32779
#define ID_ANNTEXT                      32780
#define ID_NEXTMEDIA                    32781
#define ID_PREVMEDIA                    32782
#define ID_FIRST_SHOW_ITEM              32783
#define ID_NEXT_SHOW_ITEM               32784
#define ID_PREV_SHOW_ITEM               32785
#define ID_LAST_SHOW_ITEM               32786
#define ID_MOUSE_MODE                   32787
#define ID_SHOW_TOOLBAR                 32788
#define ID_ZOOMRECTANGLE                32789
#define ID_ZOOMMODE                     32789
#define ID_ZOOM_RESTRICTED              32789
#define ID_SPLIT_VERTICAL               32790
#define ID_SPLIT_HORIZONTAL             32791
#define ID_HORIZONTAL_NEXT              32792
#define ID_SCREEN_CAPTURE               32793
#define ID_SHADEONCALLOUT               32794
#define ID_CAPTURE_BARCODES             32795
#define ID_ZAP_UPDATE                   32796
#define ID_VERTICAL_NEXT                32797
#define ID_SPLITPAGES_FIRST             32798
#define ID_SPLIT_PAGES_PREVIOUS         32799
#define ID_SPLITPAGES_NEXT              32800
#define ID_SPLITPAGES_LAST              32801
#define ID_ZAP_SAVE_SPLIT               32803
#define IDS_DBFILENOTFOUND              61204
#define IDS_OPENDBFAILED                61205
#define IDS_DBFILEINVALID               61206
#define IDS_DBNOTOPEN                   61207
#define IDS_INVALIDBARCODE              61208
#define IDS_BARCODENOTFOUND             61209
#define IDS_OPENMEDIAFROMBC             61210
#define IDS_OPENPLAYLISTFROMBC          61211
#define IDS_PLAYLISTBARCODE             61212
#define IDS_MEDIABARCODE                61213
#define IDS_NOPAGERECORD                61214
#define IDS_MEDBNOTOPEN                 61215
#define IDS_TESTNODB                    61216
#define IDS_TESTNOPLAYLISTS             61217
#define IDS_TESTNOMEDIA                 61218
#define IDS_GRAPHICNOTFOUND             61219
#define IDS_DOCNOTFOUND                 61220
#define IDS_LINKNOTFOUND                61221
#define IDS_CLIPNOTFOUND                61222
#define IDS_SETPGLN_INVALIDLINE         61223
#define IDS_SETPGLN_OUTOFRANGE          61224
#define IDS_SETPGLN_INVALIDPAGE         61225
#define IDS_SETPGLN_NOPLAYLIST          61226
#define IDS_SETPGLN_FRAMENOTFOUND       61227
#define IDS_DESIGNATIONNOTFOUND         61228
#define IDS_POWERPOINT_NOTINITIALIZED   61229
#define IDS_POWERNOTFOUND               61230
#define IDS_POWERPOINT_OUTOFRANGE       61231
#define IDS_NOMEDIARECORD               61232
#define IDS_NOMULTIPAGE                 61233
#define IDS_INVALIDMEDIATYPE            61234
#define IDS_PAGENOTFOUND                61235
#define IDS_TREATMENTNOTFOUND           61236
#define IDS_NOPLAYLIST                  61237
#define IDS_PLAYLISTNOTFOUND            61238
#define IDS_CONVERTANIMATION            61239
#define IDS_NOSHOW                      61240
#define IDS_SHOWITEMNOTFOUND            61241
#define IDS_INVALIDITEMBARCODE          61242
#define IDS_NOITEMMEDIA                 61243
#define IDS_NOITEMSECONDARY             61244
#define IDS_NONESTEDSHOWS               61245
#define IDS_NOFOREIGNCODE               61246
#define IDS_CREATECAPTUREFAILED         61247
#define IDS_CONVERTDEPOSITION           61248
#define IDS_NODEPOSITION                61249
#define IDS_TRANSRIPTNOTFOUND           61250
#define IDS_OPENTRANSCRIPTFAILED        61251
#define IDS_ZAP_FILE_NOT_FOUND          61252
#define IDS_ZAP_PAGE_NOT_FOUND          61253
#define IDS_SIBLING_NOT_FOUND           61253

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        404
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
